---
apiVersion: litmuschaos.io/v1alpha1
kind: ChartServiceVersion
metadata:
  createdAt: 2022-11-10T16:32:08Z
  name: lambda-update-function-memory
  version: 0.1.0
  annotations:
    categories: AWS
    vendor: Harness
spec:
  displayName: Lambda Update Function Memory
  categoryDescription: |
    This fault causes the memory of a lambda function to be updated to specified value.
  keywords:
    - AWS
  plan:
    - enterprise
  platforms:
    - AWS
  experiments:
    - aws-lambda-update-function-memory
  chaosType: infra
  labels:
    app.kubernetes.io/component: chartserviceversion
    app.kubernetes.io/version: ci
  links:
    - name: Documentation
      url: https://docs.harness.io/category/kl0mxwpfw1-hce-category
  icon:
    - url:
      mediatype: ""
