---
apiVersion: litmuschaos.io/v1alpha1
kind: ChartServiceVersion
metadata:
  name: kubelet-density
  version: 0.1.0
  annotations:
    categories: kube-resilience
spec:
  displayName: Kubelet Density
  categoryDescription: >
    Check Kubernetes resilience and performance upon multiple pod creation requests.
  keywords:
    - "pods"
    - "kubernetes"
  platforms:
    - "Minikube"
  maturity: alpha
  minKubeVersion: 1.12.0
  labels:
    app.kubernetes.io/component: chartserviceversion
    app.kubernetes.io/version: ci
  links:
    - name: Documentation
      url: Harness Docs
  icon:
    - url: ""
      mediatype: ""
