---
apiVersion: litmuschaos.io/v1alpha1
kind: ChaosEngine
metadata:
  name: fs-fill
  namespace: default
  labels:
    name: fs-fill
    app.kubernetes.io/part-of: litmus
    app.kubernetes.io/component: experiment-job
    app.kubernetes.io/host-path-usage: "true"
    app.kubernetes.io/version: ci
spec:
  # It can be active/stop
  engineState: "active"
  terminationGracePeriodSeconds: 30
  #ex. values: ns1:name=percona,ns2:run=nginx
  auxiliaryAppInfo: ""
  appinfo:
    appns: ""
    applabel: ""
    appkind: ""
  chaosServiceAccount: fs-fill-sa
  experiments:
    - name: fs-fill
      image: artifactory.sdlc.ctl.gcp.db.com/dkr-public-local/dkr-io/harness/chaos-go-runner:1.54.0
      imagePullPolicy: Always
      args:
        - -c
        - ./experiments -name fs-fill
      command:
        - /bin/bash
      spec:
        components:
          env:
            - name: TARGET_CONTAINER
              value: ""

            # space to be filled in bytes
            # or specify the size in 'K', 'KB', 'M', 'MB', 'G', 'GB'
            - name: FILL_SIZE
              value: "100M"

            # specify the path to fill
            - name: FILE_PATH
              value: "/tmp"

            - name: TOTAL_CHAOS_DURATION
              value: "60"

            # Period to wait before and after injection of chaos in sec
            - name: RAMP_TIME
              value: ""

            - name: TARGET_PODS
              value: ""

            # To select pods on specific node(s)
            - name: NODE_LABEL
              value: ""

            ## percentage of total pods to target
            - name: PODS_AFFECTED_PERC
              value: ""

            - name: LIB_IMAGE
              value: artifactory.sdlc.ctl.gcp.db.com/dkr-public-local/dkr-io/harness/chaos-go-runner:1.54.0

            ## it defines the sequence of chaos execution for multiple target pods
            ## supported values: serial, parallel
            - name: SEQUENCE
              value: "parallel"

            - name: CONTAINER_RUNTIME
              value: containerd

            - name: SOCKET_PATH
              value: /run/containerd/containerd.sock
