---
apiVersion: litmuschaos.io/v1alpha1
kind: ChaosEngine
metadata:
  name: gcp-vm-disk-loss
  namespace: default
  labels:
    name: gcp-vm-disk-loss
    app.kubernetes.io/part-of: litmus
    app.kubernetes.io/component: experiment-job
    app.kubernetes.io/version: ci
spec:
  # It can be active/stop
  engineState: "active"
  terminationGracePeriodSeconds: 30
  chaosServiceAccount: litmus-admin
  experiments:
    - name: gcp-vm-disk-loss
      image: artifactory.sdlc.ctl.gcp.db.com/dkr-public-local/dkr-io/harness/chaos-go-runner:1.41.0
      imagePullPolicy: Always
      args:
        - -c
        - ./experiments -name gcp-vm-disk-loss
      command:
        - /bin/bash
      spec:
        components:
          env:
            - name: TOTAL_CHAOS_DURATION
              value: "30"

            - name: CHAOS_INTERVAL
              value: "30"

            # Period to wait before and after injection of chaos in sec
            - name: RAMP_TIME
              value: ""

            # parallel or serial; determines how chaos is injected
            - name: SEQUENCE
              value: "parallel"

            # set the GCP project id
            - name: GCP_PROJECT_ID
              value: ""

            # set the disk volume name(s) as comma seperated values
            # eg. volume1,volume2,...
            - name: DISK_VOLUME_NAMES
              value: ""

            # set the disk zone(s) as comma seperated values in the corresponding
            # order of DISK_VOLUME_NAME
            # eg. zone1,zone2,...
            - name: ZONES
              value: ""

            - name: DEFAULT_HEALTH_CHECK
              value: "false"

            # parallel or serial; determines how chaos is injected
            - name: SEQUENCE
              value: "parallel"
          secrets:
            - name: cloud-secret
              mountPath: /tmp/
