---
apiVersion: litmuschaos.io/v1alpha1
kind: ChaosEngine
metadata:
  name: aws-ssm-chaos-by-id
  namespace: default
  labels:
    name: aws-ssm-chaos-by-id
    app.kubernetes.io/part-of: litmus
    app.kubernetes.io/component: experiment-job
    app.kubernetes.io/version: ci
    app.kubernetes.io/enableAWSAccessViaSecrets: disable
spec:
  engineState: "active"
  terminationGracePeriodSeconds: 30
  chaosServiceAccount: litmus-admin
  experiments:
    - name: aws-ssm-chaos-by-id
      image: artifactory.sdlc.ctl.gcp.db.com/dkr-public-local/dkr-io/harness/chaos-go-runner:1.41.0
      imagePullPolicy: Always
      args:
        - -c
        - ./experiments -name aws-ssm-chaos-by-id
      command:
        - /bin/bash
      spec:
        components:
          env:
            - name: TOTAL_CHAOS_DURATION
              value: "60"

            - name: CHAOS_INTERVAL
              value: "60"

            # Period to wait before and after injection of chaos in sec
            - name: RAMP_TIME
              value: ""

            # Instance ID of the target EC2 instance
            # Multiple IDs can also be provided as comma separated values ex: id1,id2
            - name: EC2_INSTANCE_ID
              value: ""

            - name: REGION
              value: ""

            # Provide the name of SSM doc
            - name: DOCUMENT_NAME
              value: ""

            - name: PLUGIN_NAME
              value: ""

            - name: PARAMETERS
              value: ""

            # it defines the sequence of chaos execution for multiple target instances
            # supported values: serial, parallel
            - name: SEQUENCE
              value: "parallel"

            # Provide the path of AWS credentials mounted from secret
            - name: AWS_SHARED_CREDENTIALS_FILE
              value: "/tmp/cloud_config.yml"
          projectedVolumes:
            - name: aws-iam-token
              mountPath: /var/run/secrets/eks.amazonaws.com/serviceaccount
              readOnly: true
              projected:
                defaultMode: 420
                sources:
                  - serviceAccountToken:
                      audience: sts.amazonaws.com
                      expirationSeconds: 86400
                      path: token
