---
apiVersion: litmuchaos.io/v1alpha1
kind: ChartServiceVersion
metadata:
  createdAt: 2023-11-03T04:27:08Z
  name: cf-app-network-latency
  version: 0.1.0
  annotations:
    categories: Cloud-Foundry
    vendor: Harness
spec:
  displayName: cf-app-network-latency
  categoryDescription: |
    This fault injects app network latency chaos in the Cloud Foundry platform.
    - Checks resilience against network latency in app instances
    - Helps validate the effectiveness of disaster recovery and high availability of the app
  keywords:
    - Cloud Foundry
    - CF
    - Network
    - Latency
  plan:
    - enterprise
  maturity: alpha
  labels:
    app.kubernetes.io/component: chartserviceversion
    app.kubernetes.io/version: ci
  links:
    - name: Documentation
      url: https://developer.harness.io/docs/chaos-engineering/technical-reference/chaos-faults/cloud-foundry/
  icon:
    - url:
      mediatype: ""
  experiments:
    - cf-app-network-latency
