---
apiVersion: litmuschaos.io/v1alpha1
kind: ChaosEngine
metadata:
  name: ssh-chaos
  namespace: default
  labels:
    name: ssh-chaos
    app.kubernetes.io/part-of: litmus
    app.kubernetes.io/component: experiment-job
    app.kubernetes.io/version: ci
    app.kubernetes.io/enableSSHAccessViaSecrets: disable
spec:
  engineState: "active"
  terminationGracePeriodSeconds: 30
  chaosServiceAccount: litmus-admin
  experiments:
    - name: ssh-chaos
      image: artifactory.sdlc.ctl.gcp.db.com/dkr-public-local/dkr-io/harness/chaos-go-runner:1.54.0
      imagePullPolicy: Always
      args:
        - -c
        - ./experiments -name ssh-chaos
      command:
        - /bin/bash
      spec:
        components:
          env:
            - name: RAMP_TIME
              value: ""
            - name: PRIVATE_KEY
              value: ''
            - name: CHAOS_SCRIPT_PATH
              value: '/tmp/chaos-script/script.sh'
            - name: ABORT_SCRIPT_PATH
              value: '/tmp/abort-script/abort-script.sh'
            - name: HOST
              value: ""
            - name: USERNAME
              value: ""
            - name: PASSWORD
              value: ""
            - name: CHAOS_PARAMETER
              value: ""
            - name: ABORT_PARAMETER
              value: ""
              secrets:
          secrets:
            - name: ssh-secret
              mountPath: /tmp/ssh-secret
          configMaps:
            - name: chaos-script
              mountPath: /tmp/chaos-script
            - name: abort-script
              mountPath: /tmp/abort-script
