---
apiVersion: litmuschaos.io/v1alpha1
kind: ChaosEngine
metadata:
  name: pod-cpu-hog-exec
  namespace: default
  labels:
    name: pod-cpu-hog-exec
    app.kubernetes.io/part-of: litmus
    app.kubernetes.io/component: experiment-job
    app.kubernetes.io/version: ci
spec:
  # It can be active/stop
  engineState: "active"
  terminationGracePeriodSeconds: 30
  appinfo:
    appns: ""
    applabel: ""
    appkind: ""
  chaosServiceAccount: pod-cpu-hog-exec-sa
  experiments:
    - name: pod-cpu-hog-exec
      image: artifactory.sdlc.ctl.gcp.db.com/dkr-public-local/com/db/chaos-hce/thirdparty/harness/chaos-go-runner:1.38.2
      imagePullPolicy: Always
      args:
        - -c
        - ./experiments -name pod-cpu-hog-exec
      command:
        - /bin/bash
      spec:
        components:
          env:
            - name: TOTAL_CHAOS_DURATION
              value: "60"

            ## Number of CPU cores to stress
            - name: CPU_CORES
              value: "1"

            ## Percentage of total pods to target
            - name: PODS_AFFECTED_PERC
              value: ""

            ## Period to wait before and after injection of chaos in sec
            - name: RAMP_TIME
              value: ""

            # The command to kill the chaos process
            - name: CHAOS_KILL_COMMAND
              value: "kill $(find /proc -name exe -lname '*/md5sum' 2>&1 | grep -v 'Permission denied' | awk -F/ '{print $(NF-1)}')"

            - name: TARGET_CONTAINER
              value: ""

            - name: TARGET_PODS
              value: ""

            - name: DEFAULT_HEALTH_CHECK
              value: "false"

            ## it defines the sequence of chaos execution for multiple target pods
            ## supported values: serial, parallel
            - name: SEQUENCE
              value: "parallel"
        probe:
          - name: healthcheck
            type: cmdProbe
            mode: Edge
            runProperties:
              probeTimeout: 180s
              retry: 0
              interval: 1s
              stopOnFailure: false
            cmdProbe/inputs:
              command: ./healthcheck -name pod-level
              source:
                image: artifactory.sdlc.ctl.gcp.db.com/dkr-public-local/com/db/chaos-hce/thirdparty/harness/chaos-go-runner:1.38.2
                inheritInputs: true
              comparator:
                type: string
                criteria: contains
                value: "[P000]"
