---
apiVersion: litmuschaos.io/v1alpha1
kind: ChaosEngine
metadata:
  name: vmware-http-response-modify
  labels:
    name: vmware-http-response-modify
    app.kubernetes.io/part-of: litmus
    app.kubernetes.io/component: experiment-job
    app.kubernetes.io/version: ci
spec:
  # It can be active/stop
  engineState: "active"
  terminationGracePeriodSeconds: 30
  chaosServiceAccount: litmus-admin
  experiments:
    - name: vmware-http-response-modify
      image: artifactory.sdlc.ctl.gcp.db.com/dkr-public-local/dkr-io/harness/chaos-go-runner:1.54.0
      imagePullPolicy: Always
      args:
        - -c
        - ./experiments -name vmware-http-response-modify
      command:
        - /bin/bash
      spec:
        components:
          env:

            # provide lib image
            - name: LIB_IMAGE
              value: artifactory.sdlc.ctl.gcp.db.com/dkr-public-local/dkr-io/harness/chaos-go-runner:1.54.0

            # provide the http chaos type for modify response
            # accepted values are status_code, body, header
            - name: HTTP_CHAOS_TYPE
              value: 'status_code'

            # modified status code for the http response
            # if no value is provided, a random status code from the supported code list will selected
            # if an invalid status code is provided, the experiment will fail
            # supported status code list: [200, 201, 202, 204, 300, 301, 302, 304, 307, 400, 401, 403, 404, 500, 501, 502, 503, 504
            - name: STATUS_CODE
              value: ''

            #  whether to modify the body as per the status code provided
            - name: MODIFY_RESPONSE_BODY
              value: "true"

            # provide the body string to overwrite the response body
            - name: RESPONSE_BODY
              value: ''

            # map of headers to modify/add; Eg: {"X-Litmus-Test-Header": "X-Litmus-Test-Value"}
            # to remove a header, just set the value to ""; Eg: {"X-Litmus-Test-Header": ""}
            - name: HEADERS_MAP
              value: '{}'

            # whether to modify response headers or request headers. Accepted values: request, response
            - name: HEADER_MODE
              value: 'response'

            # port of the target service
            - name: TARGET_SERVICE_PORT
              value: "80"

            # port on which the proxy will listen
            - name: PROXY_PORT
              value: "8080"

            # network interface on which the proxy will listen
            - name: NETWORK_INTERFACE
              value: "ens160"

            - name: VM_NAME
              value: ''

            - name: VM_USER_NAME
              value: ''

            - name: VM_PASSWORD
              value: ''

            - name: TOTAL_CHAOS_DURATION
              value: '60' # in seconds

            - name: CHAOS_INTERVAL
              value: '60'

            # Time period to wait before and after injection of chaos in sec
            - name: RAMP_TIME
              value: ''

            ## it defines the sequence of chaos execution for multiple target vms
            ## supported values: serial, parallel
            - name: SEQUENCE
              value: 'parallel'

            - name: DEFAULT_HEALTH_CHECK
              value: 'false'

            - name: GOVC_URL
              valueFrom:
                secretKeyRef:
                  name: vcenter-secret
                  key: VCENTERSERVER

            - name: GOVC_USERNAME
              valueFrom:
                secretKeyRef:
                  name: vcenter-secret
                  key: VCENTERUSER

            - name: GOVC_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: vcenter-secret
                  key: VCENTERPASS

            - name: GOVC_INSECURE
              value: 'true'
