apiVersion: litmuschaos.io/v1alpha1
kind: ChaosEngine
metadata:
  name: nginx-chaos
  namespace: default
spec:
  components:
    runner:
      # secret name for the runner image, if using private registry
      imagePullSecrets:
      - name: regcred
      runnerAnnotations:
        sidecar.istio.io/inject: "false"
  # It can be active/stop
  engineState: 'active'
  #ex. values: ns1:name=percona,ns2:run=nginx 
  auxiliaryAppInfo: ''
  appinfo:
    appns: 'default'
    applabel: 'app=nginx'
    appkind: 'deployment'
  chaosServiceAccount: pod-autoscaler-sa
  experiments:
    - name: pod-autoscaler
      spec:
          components:
            # secret name for the experiment image, if using private registry
            experimentImagePullSecrets:
            - name: regcred
            experimentAnnotations:
              sidecar.istio.io/inject: "false"
          env:
            # set chaos duration (in sec) as desired
            - name: TOTAL_CHAOS_DURATION
              value: '60'

            # number of replicas to scale
            - name: REPLICA_COUNT
              value: '5'
              