---
apiVersion: litmuschaos.io/v1alpha1
kind: ChaosEngine
metadata:
  name: vmware-windows-cpu-hog
  namespace: default
  labels:
    name: vmware-windows-cpu-hog
    app.kubernetes.io/part-of: litmus
    app.kubernetes.io/component: experiment-job
    app.kubernetes.io/version: ci

spec:
  engineState: "active"
  terminationGracePeriodSeconds: 30
  chaosServiceAccount: litmus-admin
  experiments:
    - name: vmware-cpu-hog
      image: artifactory.sdlc.ctl.gcp.db.com/dkr-public-local/dkr-io/harness/chaos-go-runner:1.54.0
      imagePullPolicy: Always
      args:
        - -c
        - ./experiments -name vmware-windows-cpu-hog
      command:
        - /bin/bash
      spec:
        components:
          env:
            - name: TOTAL_CHAOS_DURATION
              value: "60"

            - name: VM_NAME
              value: ""

            - name: VM_USER_NAME
              value: ""

            - name: VM_PASSWORD
              value: ""

            - name: CPU_CORES
              value: "0"

            - name: CPU_PERCENTAGE
              value: "0"

            - name: RAMP_TIME
              value: ""

            - name: SEQUENCE
              value: "parallel"

            - name: GOVC_URL
              valueFrom:
                secretKeyRef:
                  name: vcenter-secret
                  key: VCENTERSERVER

            - name: GOVC_USERNAME
              valueFrom:
                secretKeyRef:
                  name: vcenter-secret
                  key: VCENTERUSER

            - name: GOVC_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: vcenter-secret
                  key: VCENTERPASS

            - name: GOVC_INSECURE
              value: "true"
