---
apiVersion: litmuschaos.io/v1alpha1
kind: ChaosEngine
metadata:
  name: azure-instance-io-stress
  namespace: default
  labels:
    name: azure-instance-io-stress
    app.kubernetes.io/part-of: litmus
    app.kubernetes.io/component: experiment-job
    app.kubernetes.io/version: ci
spec:
  engineState: "active"
  terminationGracePeriodSeconds: 30
  chaosServiceAccount: litmus-admin
  experiments:
    - name: azure-instance-io-stress
      image: artifactory.sdlc.ctl.gcp.db.com/dkr-public-local/dkr-io/harness/chaos-go-runner:1.54.0
      imagePullPolicy: Always
      args:
        - -c
        - ./experiments -name azure-instance-io-stress
      command:
        - /bin/bash
      spec:
        components:
          env:
            - name: TOTAL_CHAOS_DURATION
              value: "30"

            - name: CHAOS_INTERVAL
              value: "30"

            - name: RAMP_TIME
              value: ""

            - name: AZURE_INSTANCE_NAMES
              value: ""

            - name: RESOURCE_GROUP
              value: ""

            - name: SCALE_SET
              value: ""

            - name: FILESYSTEM_UTILIZATION_BYTES
              value: "5"

            - name: FILESYSTEM_UTILIZATION_PERCENTAGE
              value: "0"

            - name: NUMBER_OF_WORKERS
              value: "1"

            - name: VOLUME_MOUNT_PATH
              value: /tmp

            - name: AZURE_AUTH_LOCATION
              value: /tmp/azure.auth

            - name: SEQUENCE
              value: parallel

            - name: DEFAULT_HEALTH_CHECK
              value: "false"
          secrets:
            - name: cloud-secret
              mountPath: /tmp/
