---
apiVersion: litmuschaos.io/v1alpha1
kind: ChartServiceVersion
metadata:
  name: pod-jvm-sql-exception
  version: 0.1.0
  annotations:
    categories: Kubernetes
    vendor: Harness
spec:
  displayName: Pod JVM SQL Exception
  categoryDescription: |
    This fault injects JVM SQL Exception chaos inside a Java process executing in a Kubernetes pod.
  keywords:
    - Kubernetes
  plan:
    - free
  platforms:
    - GKE
    - Packet(Kubeadm)
    - Minikube
    - EKS
    - AKS
    - OpenShift(OKD)
  minKubeVersion: 1.12.0
  labels:
    app.kubernetes.io/component: chartserviceversion
    app.kubernetes.io/version: ci
  links:
    - name: Documentation
      url: https://docs.harness.io/category/kl0mxwpfw1-hce-category
  icon:
    - base64data: ""
      mediatype: ""
