---
apiVersion: litmuschaos.io/v1alpha1
kind: K8sFault
metadata:
  name: pod-network-latency
spec:
  definition:
    targets:
      appinfo:
        applabel: ""
        appkind: ""
        appns: ""
    chaos:
      experiment: pod-network-latency
      serviceAccountName: litmus-admin
      image: artifactory.sdlc.ctl.gcp.db.com/dkr-public-local/dkr-io/harness/chaos-ddcr-faults:1.54.0
      imagePullPolicy: Always
      env:
        - name: TOTAL_CHAOS_DURATION
          value: "60" # in seconds

        - name: NETWORK_LATENCY
          value: "2s"

        - name: CORRELATION
          value: ""

        - name: JITTER
          value: "0"

        # provide the name of container runtime
        # for litmus LIB, it supports docker, containerd, crio
        - name: CONTAINER_RUNTIME
          value: "containerd"

        # provide the socket file path
        - name: SOCKET_PATH
          value: "/run/containerd/containerd.sock"

        - name: LIB_IMAGE
          value: artifactory.sdlc.ctl.gcp.db.com/dkr-public-local/dkr-io/harness/chaos-ddcr-faults:1.54.0

        ## percentage of total pods to target
        - name: POD_AFFECTED_PERCENTAGE
          value: ""

        - name: NETWORK_INTERFACE
          value: "eth0"

        # Time period to wait before and after injection of chaos in sec
        - name: RAMP_TIME
          value: ""

        - name: TARGET_PODS
          value: ""

        # provide the destination ips
        # chaos injection will be triggered for these destination ips
        - name: DESTINATION_IPS
          value: ""

        # provide the destination hosts
        # chaos injection will be triggered for these destination hosts
        - name: DESTINATION_HOSTS
          value: ""

        # provide the comma seperated source ports
        - name: SOURCE_PORTS
          value: ""

        # provide the comma seperated destination ports
        - name: DESTINATION_PORTS
          value: ""

        # To select pods on specific node(s)
        - name: NODE_LABEL
          value: ""

        ## it defines the sequence of chaos execution for multiple target pods
        ## supported values: serial, parallel
        - name: SEQUENCE
          value: "parallel"
