---
apiVersion: litmuschaos.io/v1alpha1
kind: ChaosEngine
metadata:
  name: windows-ec2-blackhole-chaos
  namespace: default
  labels:
    name: windows-ec2-blackhole-chaos
    app.kubernetes.io/part-of: litmus
    app.kubernetes.io/component: experiment-job
    app.kubernetes.io/version: ci
    app.kubernetes.io/enableAWSAccessViaSecrets: disable
spec:
  engineState: "active"
  terminationGracePeriodSeconds: 30
  chaosServiceAccount: litmus-admin
  experiments:
    - name: windows-ec2-blackhole-chaos
      image: artifactory.sdlc.ctl.gcp.db.com/dkr-public-local/dkr-io/harness/chaos-go-runner:1.54.0
      imagePullPolicy: Always
      args:
        - -c
        - ./experiments -name ec2-blackhole-chaos
      command:
        - /bin/bash
      spec:
        components:
          env:
            - name: TOTAL_CHAOS_DURATION
              value: "60"
            - name: RAMP_TIME
              value: ""
            - name: EC2_INSTANCE_ID
              value: ""
            - name: REGION
              value: ""
            - name: EC2_INSTANCE_TAG
              value: ""
            - name: IP_ADDRESSES
              value: ""
            - name: DESTINATION_HOSTS
              value: ""
            - name: AWS_SHARED_CREDENTIALS_FILE
              value: /tmp/cloud_config.yml
            - name: SEQUENCE
              value: "parallel"
          projectedVolumes:
            - name: aws-iam-token
              mountPath: /var/run/secrets/eks.amazonaws.com/serviceaccount
              readOnly: true
              projected:
                defaultMode: 420
                sources:
                  - serviceAccountToken:
                      audience: sts.amazonaws.com
                      expirationSeconds: 86400
                      path: token
