---
apiVersion: litmuschaos.io/v1alpha1
kind: ChartServiceVersion
metadata:
  createdAt: 2022-07-18T10:28:08Z
  name: windows-ec2-blackhole-chaos
  version: 0.1.0
  annotations:
    categories: AWS
    vendor: Harness
spec:
  displayName: Windows EC2 CPU Hog
  categoryDescription: |
    Windows EC2 blackhole chaos fault disrupts the state of the windows EC2 instance. This fault injects the blackhole chaos on the target windows EC2 instances.
    - Causes the network unavailability in the target windows EC2 instances.
    - It can help in checking the performance of the application running on an windows EC2 instance when subjected to CPU stress.
  keywords:
    - AWS
    - Windows
  plan:
    - team
  platforms:
    - GKE
    - EKS
  experiments:
    - aws-windows-ec2-blackhole-chaos
  minKubeVersion: 1.12.0
  labels:
    app.kubernetes.io/component: chartserviceversion
    app.kubernetes.io/version: ci
  links:
    - name: Documentation
      url: https://docs.harness.io/category/kl0mxwpfw1-hce-category
  icon:
    - url:
      mediatype: ""
