---
apiVersion: litmuschaos.io/v1alpha1
kind: ChartServiceVersion
metadata:
  name: redis-cache-penetration
  version: 0.1.0
  annotations:
    categories: Kubernetes
    vendor: Harness
spec:
  displayName: Redis Cache Penetration
  categoryDescription: |
    This fault causes Redis cache penetration.
    - An inexistent key is attempted to be accessed frequently for a given count value.
    - Determines the resiliency of Redis against frequent cache miss.
  keywords:
    - Redis
  plan:
    - free
  platforms:
    - GKE
    - Packet(Kubeadm)
    - Minikube
    - EKS
    - AKS
    - OpenShift(OKD)
  minKubeVersion: 1.12.0
  labels:
    app.kubernetes.io/component: chartserviceversion
    app.kubernetes.io/version: ci
  links:
    - name: Documentation
      url: https://docs.harness.io/category/kl0mxwpfw1-hce-category
  icon:
    - base64data: ""
      mediatype: ""
