---
apiVersion: litmuschaos.io/v1alpha1
kind: K8sFault
metadata:
  name: gcp-vm-service-kill
spec:
  definition:
    chaos:
      experiment: gcp-vm-service-kill
      serviceAccountName: litmus-admin
      image: artifactory.sdlc.ctl.gcp.db.com/dkr-public-local/dkr-io/harness/chaos-ddcr-faults:1.54.0
      imagePullPolicy: Always
      env:
        - name: TOTAL_CHAOS_DURATION
          value: "90" # in seconds

        - name: NODE_LABEL
          value: ""

        - name: VM_INSTANCE_NAME
          value: ""

        - name: LIB_IMAGE
          value: harness/chaos-ddcr-faults:1.54.0

        - name: SERVICE_NAME
          value: 'containerd'

        - name: MASK
          value: 'disable'

        - name: VM_USERNAME
          value: ''

        - name: SUDO_ENABLED
          value: 'true'

        - name: ZONE
          value: ""

        - name: SET_HELPER_DATA
          value: 'true'

        # GCP project ID to which the VM instances belong
        - name: GCP_PROJECT_ID
          value: ""

        ## Period to wait before and after injection of chaos in sec
        - name: RAMP_TIME
          value: ""

      components:
        secrets:
          - name: cloud-secret
            mountPath: /tmp/
