---
apiVersion: litmuschaos.io/v1alpha1
kind: ChaosEngine
metadata:
  name: time-chaos
  namespace: default
  labels:
    name: time-chaos
    app.kubernetes.io/part-of: litmus
    app.kubernetes.io/component: experiment-job
    app.kubernetes.io/version: ci
spec:
  # It can be active/stop
  engineState: "active"
  terminationGracePeriodSeconds: 30
  appinfo:
    appns: ""
    # FYI, To see app label, apply kubectl get pods --show-labels
    applabel: ""
    appkind: ""
  chaosServiceAccount: time-chaos-sa
  experiments:
    - name: time-chaos
      image: artifactory.sdlc.ctl.gcp.db.com/dkr-public-local/com/db/chaos-hce/harness/chaos-go-runner-time:1.38.2
      imagePullPolicy: Always
      args:
        - -c
        - ./experiments -name time-chaos
      command:
        - /bin/bash
      spec:
        components:
          env:
            - name: TOTAL_CHAOS_DURATION
              value: "60" # in seconds

            # time period to wait before and after injection of chaos in sec
            - name: RAMP_TIME
              value: ""

            # offset for altering the time
            - name: OFFSET
              value: "3600s"

            # target system clock id; refer 'uapi/linux/time.h' for more details
            - name: CLOCK_IDS
              value: "CLOCK_REALTIME"

            - name: TARGET_CONTAINER
              value: ""

            # provide lib image
            - name: LIB_IMAGE
              value: artifactory.sdlc.ctl.gcp.db.com/dkr-public-local/com/db/chaos-hce/harness/chaos-go-runner-time:1.38.2

            # percentage of total pods to target
            - name: PODS_AFFECTED_PERC
              value: ""

            - name: DEFAULT_HEALTH_CHECK
              value: "false"

            - name: TARGET_PODS
              value: ""

            # To select pods on specific node(s)
            - name: NODE_LABEL
              value: ""

            # provide the name of container runtime
            # for litmus LIB, it supports docker, containerd, crio
            - name: CONTAINER_RUNTIME
              value: "containerd"

            # provide the socket file path
            - name: SOCKET_PATH
              value: "/run/containerd/containerd.sock"

            ## it defines the sequence of chaos execution for multiple target pods
            ## supported values: serial, parallel
            - name: SEQUENCE
              value: "parallel"

        probe:
          - name: healthcheck
            type: cmdProbe
            mode: Edge
            runProperties:
              probeTimeout: 180s
              retry: 0
              interval: 1s
              stopOnFailure: false
            cmdProbe/inputs:
              command: ./healthcheck -name pod-level
              source:
                image: artifactory.sdlc.ctl.gcp.db.com/dkr-public-local/com/db/chaos-hce/thirdparty/harness/chaos-go-runner:1.38.2
                inheritInputs: true
              comparator:
                type: string
                criteria: contains
                value: "[P000]"
