---
apiVersion: litmuschaos.io/v1alpha1
kind: ChaosEngine
metadata:
  name: ecs-fargate-memory-hog
  namespace: default
  labels:
    name: ecs-fargate-memory-hog
    app.kubernetes.io/part-of: litmus
    app.kubernetes.io/component: experiment-job
    app.kubernetes.io/version: ci
    app.kubernetes.io/enableAWSAccessViaSecrets: disable
spec:
  engineState: "active"
  terminationGracePeriodSeconds: 30
  chaosServiceAccount: litmus-admin
  experiments:
    - name: ecs-fargate-cpu-hog
      image: artifactory.sdlc.ctl.gcp.db.com/dkr-public-local/com/db/chaos-hce/thirdparty/harness/chaos-go-runner:1.41.0
      imagePullPolicy: Always
      args:
        - -c
        - ./experiments -name ecs-fargate-memory-hog
      command:
        - /bin/bash
      spec:
        components:
          env:
            - name: TOTAL_CHAOS_DURATION
              value: "30"
            - name: CHAOS_INTERVAL
              value: "30"
            - name: RAMP_TIME
              value: ""
            - name: CLUSTER_NAME
              value: ""
            - name: SERVICE_NAME
              value: ""
            - name: MEMORY_IN_MEGABYTE
              value: "500"
            - name: CONTAINER_IMAGE
              value: artifactory.sdlc.ctl.gcp.db.com/dkr-public-local/com/db/chaos-hce/thirdparty/harness/chaos-go-runner:1.41.0
            - name: REGION
              value: ""
            - name: TASK_REPLICA_AFFECTED_PERC
              value: "100"
            - name: AWS_SHARED_CREDENTIALS_FILE
              value: /tmp/cloud_config.yml
          projectedVolumes:
            - name: aws-iam-token
              mountPath: /var/run/secrets/eks.amazonaws.com/serviceaccount
              readOnly: true
              projected:
                defaultMode: 420
                sources:
                  - serviceAccountToken:
                      audience: sts.amazonaws.com
                      expirationSeconds: 86400
                      path: token
