---
apiVersion: litmuschaos.io/v1alpha1
kind: K8sFault
metadata:
  name: ecs-fargate-memory-hog
spec:
  definition:
    chaos:
      experiment: ecs-fargate-memory-hog
      serviceAccountName: litmus-admin
      image: artifactory.sdlc.ctl.gcp.db.com/dkr-public-local/dkr-io/harness/chaos-ddcr-faults:1.54.0
      imagePullPolicy: Always
      env:
        - name: TOTAL_CHAOS_DURATION
          value: "30"

        - name: CHAOS_INTERVAL
          value: "30"

        - name: CLUSTER_NAME
          value: ""

        - name: SERVICE_NAME
          value: ""

        - name: REGION
          value: ""

        - name: MEMORY_IN_MEGABYTE
          value: "500"

        - name: SIDECAR_CONTAINER
          value: "default"

        - name: CONTAINER_IMAGE
          value: artifactory.sdlc.ctl.gcp.db.com/dkr-public-local/dkr-io/harness/chaos-go-runner:1.54.0

        - name: TASK_REPLICA_AFFECTED_PERC
          value: "100"

        - name: RAMP_TIME
          value: ""
