---
apiVersion: litmuschaos.io/v1alpha1
kind: ChaosEngine
metadata:
  name: azure-web-app-stop
  namespace: default
  labels:
    name: azure-web-app-stop
    app.kubernetes.io/part-of: litmus
    app.kubernetes.io/component: experiment-job
    app.kubernetes.io/version: ci
spec:
  engineState: "active"
  terminationGracePeriodSeconds: 30
  chaosServiceAccount: litmus-admin
  experiments:
    - name: azure-web-app-stop
      image: artifactory.sdlc.ctl.gcp.db.com/dkr-public-local/dkr-io/harness/chaos-go-runner:1.41.0
      imagePullPolicy: Always
      args:
        - -c
        - ./experiments -name azure-web-app-stop
      command:
        - /bin/bash
      spec:
        components:
          env:
            - name: TOTAL_CHAOS_DURATION
              value: "30"
            - name: CHAOS_INTERVAL
              value: "30"
            - name: RAMP_TIME
              value: ""
            - name: AZURE_WEB_APP_NAMES
              value: ""
            - name: RESOURCE_GROUP
              value: ""
            - name: AZURE_AUTH_LOCATION
              value: /tmp/azure.auth
            - name: SEQUENCE
              value: parallel
            - name: DEFAULT_HEALTH_CHECK
              value: "false"
          secrets:
            - name: cloud-secret
              mountPath: /tmp/
