---
apiVersion: litmuschaos.io/v1alpha1
kind: K8sFault
metadata:
  name: ecs-container-volume-detach
spec:
  definition:
    chaos:
      experiment: ecs-container-volume-detach
      serviceAccountName: litmus-admin
      image: artifactory.sdlc.ctl.gcp.db.com/dkr-public-local/dkr-io/harness/chaos-ddcr-faults:1.54.0
      imagePullPolicy: Always
      env:
        - name: TOTAL_CHAOS_DURATION
          value: "30"

        - name: CHAOS_INTERVAL
          value: "30"

        - name: CLUSTER_NAME
          value: ""

        - name: SERVICE_NAME
          value: ""

        - name: REGION
          value: ""

        - name: REQUIRED_COMPATIBILITIES
          value: "fargate,ec2"

        - name: TASK_REPLICA_AFFECTED_PERC
          value: "100"

        - name: RAMP_TIME
          value: ""
