---
apiVersion: litmuschaos.io/v1alpha1
kind: ChartServiceVersion
metadata:
  createdAt: 2022-07-26T10:28:08Z
  name: vmware-network-latency
  version: 0.1.0
  annotations:
    categories: VMWare
    vendor: Harness
spec:
  displayName: VMware Network Latency
  categoryDescription: |
    VMware network latency fault disrupts network connectivity of the VM(s).
    - It causes flaky access to the application/services by injecting network delay.
  keywords:
    - VMware

  platforms:
    - VMware
  experiments:
    - vmware-network-latency
  minKubeVersion: 1.12.0
  labels:
    app.kubernetes.io/component: chartserviceversion
    app.kubernetes.io/version: ci
  links:
    - name: Documentation
      url: https://docs.harness.io/category/kl0mxwpfw1-hce-category
  icon:
    - url:
      mediatype: ""
