apiVersion: v1
kind: ConfigMap
metadata:
  name: composer-pre-post-scripts
data:
  pre-script.sh: |
    #!/bin/bash

    # Taking backup of all existing PDBs
    kubectl get pdb --all-namespaces -o=jsonpath='{range .items[*]}{.metadata.name}{"\t"}{.metadata.namespace}{"\t"}{.spec.minAvailable}{"\n"}{end}' | grep -P '\t[1-9]+' >> pdb_namespace_originalMinimalAvailable_list.txt

    # Updating minAvailable of all PDBs to 0
    while read p; do \
    PDB=$(echo $p | awk '{print $1}') ; \
    echo PDB: ${PDB} ; \
    NS=$(echo $p | awk '{print $2}') ; \
    echo NS: ${NS} ; \
    kubectl patch pdb $PDB -n $NS --type=merge -p '{"spec":{"minAvailable":0}}' ; \
    done <  pdb_namespace_originalMinimalAvailable_list.txt

    echo "Done"
  post-script.sh: |
    #!/bin/bash

    echo "Reverting all PDBs to their backked up values"
    # Reverting all PDBs to their backked up values
    while read p; do \
    PDB=$(echo $p | awk '{print $1}') ; \
    echo PDB: ${PDB} ; \
    NS=$(echo $p | awk '{print $2}') ; \
    echo NS: ${NS} ; \
    Original_Min_Available=$(echo $p | awk '{print $3}') ; \
    echo  Original_Min_Available: ${Original_Min_Available} ; \
    command=`echo "kubectl patch pdb ${PDB} -n ${NS} --type=merge -p 
    '{\"spec\":{\"minAvailable\":${Original_Min_Available}}}'"` ;\
    echo ${command} ;\
    eval ${command} ;\
    done < pdb_namespace_originalMinimalAvailable_list.txt

    echo "Done"
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: sample-pdb
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: zookeeper