---
apiVersion: litmuschaos.io/v1alpha1
kind: ChartServiceVersion
metadata:
  createdAt: 2024-04-26T10:28:08Z
  name: fis-dynamodb-replication-pause
  version: 0.1.0
  annotations:
    categories: Kube AWS
    vendor: Harness
spec:
  displayName: FIS DynamoDB Replication Pause
  categoryDescription: |
    The fault causes DynamoDB table replication pause using AWS FIS experiment for a specified chaos duration.
  keywords:
    - AWS
  plan:
    - team
  platforms:
    - GKE
    - Packet(Kubeadm)
    - Minikube
    - EKS
    - AKS
  experiments:
    - aws-fis-dynamodb-replication-pause
  minKubeVersion: 1.12.0
  labels:
    app.kubernetes.io/component: chartserviceversion
    app.kubernetes.io/version: ci
  links:
    - name: Documentation
      url: https://docs.harness.io/category/kl0mxwpfw1-hce-category
  icon:
    - url:
      mediatype: ""
