---
apiVersion: litmuchaos.io/v1alpha1
kind: ChartServiceVersion
metadata:
  createdAt: 2024-10-01T10:28:08Z
  name: windows-process-kill
  version: 0.1.0
  annotations:
    categories: Windows
    vendor: Harness
spec:
  displayName: windows-process-kill
  categoryDescription: |
    This fault injects process kill into a windows machine.
    - Induces process kill using the process IDs and process name.
    - Simulates loss of processes, leading to degradation in the performance of application on the machine.
  keywords:
    - Windows
    - Process
  plan:
    - team
  maturity: alpha
  labels:
    app.kubernetes.io/component: chartserviceversion
    app.kubernetes.io/version: ci
  links:
    - name: Documentation
      url: https://developer.harness.io/docs/chaos-engineering/technical-reference/chaos-faults/windows/
  icon:
    - url:
      mediatype: ""
  experiments:
    - windows-process-kill
