---
apiVersion: litmuschaos.io/v1alpha1
kind: ChaosEngine
metadata:
  name: pod-dns-spoof
  labels:
    experiment: pod-dns-spoof
    app.kubernetes.io/part-of: litmus
    app.kubernetes.io/component: experiment-job
    app.kubernetes.io/runtime-api-usage: "true"
    app.kubernetes.io/version: ci
spec:
  appinfo:
    appns: ""
    applabel: ""
    appkind: ""
  # It can be active/stop
  engineState: "active"
  terminationGracePeriodSeconds: 30
  #ex. values: ns1:name=percona,ns2:run=nginx
  auxiliaryAppInfo: ""
  chaosServiceAccount: pod-dns-spoof-sa
  experiments:
    - name: pod-dns-spoof
      image: artifactory.sdlc.ctl.gcp.db.com/dkr-public-local/dkr-io/harness/chaos-go-runner:1.41.0
      imagePullPolicy: Always
      args:
        - -c
        - ./experiments -name pod-dns-spoof
      command:
        - /bin/bash
      spec:
        components:
          env:
            - name: TARGET_CONTAINER
              value: ""

            # provide lib image
            - name: LIB_IMAGE
              value: artifactory.sdlc.ctl.gcp.db.com/dkr-public-local/dkr-io/harness/chaos-go-runner:1.41.0

            - name: DEFAULT_HEALTH_CHECK
              value: "false"

            - name: TOTAL_CHAOS_DURATION
              value: "60" # in seconds

            # Time period to wait before and after injection of chaos in sec
            - name: RAMP_TIME
              value: ""

            ## percentage of total pods to target
            - name: PODS_AFFECTED_PERC
              value: ""

            - name: TARGET_PODS
              value: ""

            # provide the name of container runtime, it supports docker, containerd, crio
            - name: CONTAINER_RUNTIME
              value: "containerd"

            # provide the socket file path
            - name: SOCKET_PATH
              value: "/run/containerd/containerd.sock"

            ## it defines the sequence of chaos execution for multiple target pods
            ## supported values: serial, parallel
            - name: SEQUENCE
              value: "parallel"

            # map of the target hostnames eg. '{"abc.com":"spoofabc.com"}' . If empty no queries will be spoofed
            - name: SPOOF_MAP
              value: '{"google.com":"fakegoogle.com"}'
