---
apiVersion: litmuschaos.io/v1alpha1
kind: ChartServiceVersion
metadata:
  name: redis-cache-expire
  version: 0.1.0
  annotations:
    categories: Kubernetes
    vendor: Harness
spec:
  displayName: Redis Cache Expire
  categoryDescription: |
    This fault causes Redis cache expiration.
    - Expires a given key or all keys.
    - Determines the resiliency of Redis dependent apps against frequent cache expiration.
  keywords:
    - Redis
  plan:
    - free
  platforms:
    - GKE
    - Packet(Kubeadm)
    - Minikube
    - EKS
    - AKS
    - OpenShift(OKD)
  minKubeVersion: 1.12.0
  labels:
    app.kubernetes.io/component: chartserviceversion
    app.kubernetes.io/version: ci
  links:
    - name: Documentation
      url: https://docs.harness.io/category/kl0mxwpfw1-hce-category
  icon:
    - base64data: ""
      mediatype: ""
