---
apiVersion: litmuschaos.io/v1alpha1
kind: ChartServiceVersion
metadata:
  name: kubernetes
  version: 0.1.0
  annotations:
    categories: Kubernetes
    chartDescription: Injects kubernetes chaos experiment
    executionPlane: "kubernetes"
spec:
  displayName: Kubernetes
  categoryDescription: >
    Kubernetes is an open-source system for automating deployment, scaling, and management of containerized applications. It groups containers that make up an application into logical units for easier management and discovery. It will install all the experiments which can be used to inject chaos into containerized applications.
  faults:
    - name: pod-delete
      description: It injects pod-delete chaos in a Kubernetes pod.
      displayName: "Pod Delete"
      plan:
        - free
      supportedVersion:
        - v1
        - v2
    - name: container-kill
      description: It injects container-kill chaos in a Kubernetes pod .
      displayName: "Container Kill"
      plan:
        - free
      supportedVersion:
        - v1
        - v2
    - name: pod-cpu-hog
      description: It injects cpu-hog chaos in a Kubernetes pod.
      displayName: "Pod CPU Hog"
      plan:
        - free
      supportedVersion:
        - v1
        - v2
    - name: pod-network-loss
      description: It injects network-loss chaos in a Kubernetes pod.
      displayName: "Pod Network Loss"
      plan:
        - free
      supportedVersion:
        - v1
        - v2
    - name: pod-network-latency
      description: It injects network-latency chaos in a Kubernetes pod.
      displayName: "Pod Network Latency"
      plan:
        - free
      supportedVersion:
        - v1
        - v2
    - name: pod-network-corruption
      description: It injects network-corruption chaos in a Kubernetes pod.
      displayName: "Pod Network Corruption"
      plan:
        - free
      supportedVersion:
        - v1
        - v2
    - name: node-drain
      description: It injects node-drain chaos in a Kubernetes node.
      displayName: "Node Drain"
      chaosType: infra
      plan:
        - free
      supportedVersion:
        - v1
        - v2
    - name: node-network-loss
      description: It injects network loss chaos in a Kubernetes node.
      displayName: "Node Network Loss"
      chaosType: infra
      plan:
        - free
      supportedVersion:
        - v1
        - v2
    - name: node-cpu-hog
      description: It injects node-cpu-hog chaos in a Kubernetes node.
      displayName: "Node CPU Hog"
      chaosType: infra
      plan:
        - free
      supportedVersion:
        - v1
        - v2
    - name: node-network-latency
      description: It injects node-network-latency chaos in a Kubernetes node.
      displayName: "Node Network Latency"
      chaosType: infra
      plan:
        - free
      supportedVersion:
        - v1
        - v2
    - name: node-restart
      description: It injects node-restart chaos in a Kubernetes node.
      displayName: "Node Restart"
      chaosType: infra
      plan:
        - free
      supportedVersion:
        - v1
        - v2
    - name: disk-fill
      description: It injects disk-fill chaos in a Kubernetes node.
      displayName: "Disk Fill"
      plan:
        - free
      supportedVersion:
        - v1
        - v2
    - name: fs-fill
      description: It injects fs-fill chaos in a Kubernetes node.
      displayName: "FS Fill"
      plan:
        - free
      supportedVersion:
        - v1
        - v2
    - name: node-memory-hog
      description: It injects node-memory-hog chaos in a Kubernetes node.
      displayName: "Node Memory Hog"
      chaosType: infra
      plan:
        - free
      supportedVersion:
        - v1
        - v2
    - name: pod-memory-hog
      description: It injects pod-memory-hog chaos in a Kubernetes pod.
      displayName: "Pod Memory Hog"
      plan:
        - free
      supportedVersion:
        - v1
        - v2
    - name: kubelet-service-kill
      description: It injects kubelet-service-kill chaos in a Kubernetes node.
      displayName: "Kubelet Service Kill"
      chaosType: infra
      supportedVersion:
        - v1
        - v2
    - name: pod-network-duplication
      description: It injects pod-network-duplication chaos in a Kubernetes pod.
      displayName: "Pod Network Duplication"
      supportedVersion:
        - v1
        - v2
    - name: node-taint
      description: It injects node-taint chaos in a Kubernetes node.
      displayName: "Node Taint"
      chaosType: infra
      supportedVersion:
        - v1
        - v2
    - name: pod-autoscaler
      description: It injects pod-autoscaler chaos in a Kubernetes pod.
      displayName: "Pod Autoscaler"
      plan:
        - free
      supportedVersion:
        - v1
        - v2
    - name: node-io-stress
      description: It injects node-io-stress chaos in a Kubernetes node.
      displayName: "Node IO Stress"
      chaosType: infra
      plan:
        - free
      supportedVersion:
        - v1
        - v2
    - name: pod-io-stress
      description: It injects pod-io-stress chaos in a Kubernetes pod.
      displayName: "Pod IO Stress"
      plan:
        - free
      supportedVersion:
        - v1
        - v2
    - name: pod-dns-error
      description: It injects pod-dns-error chaos in a Kubernetes pod.
      displayName: "Pod DNS Error"
      plan:
        - free
      supportedVersion:
        - v1
        - v2
    - name: pod-dns-spoof
      description: It injects pod-dns-spoof chaos in a Kubernetes pod.
      displayName: "Pod DNS Spoof"
      plan:
        - free
      supportedVersion:
        - v1
        - v2
    - name: pod-cpu-hog-exec
      description: It injects pod-cpu-hog-exec chaos in a Kubernetes pod.
      displayName: "Pod CPU Hog Exec"
      plan:
        - free
      supportedVersion:
        - v1
    - name: pod-memory-hog-exec
      description: It injects pod-memory-hog-exec chaos in a Kubernetes pod.
      displayName: "Pod Memory Hog Exec"
      plan:
        - free
      supportedVersion:
        - v1
    - name: pod-network-partition
      description: It injects pod-network-partition chaos in a Kubernetes pod.
      displayName: "Pod Network Partition"
      plan:
        - free
      supportedVersion:
        - v1
        - v2
    - name: pod-http-latency
      description: It injects pod-http-latency chaos in a Kubernetes pod.
      displayName: "Pod HTTP Latency"
      plan:
        - free
      supportedVersion:
        - v1
        - v2
    - name: pod-http-status-code
      description: It injects pod-http-status-code chaos in a Kubernetes pod.
      displayName: "Pod HTTP Status Code"
      plan:
        - free
      supportedVersion:
        - v1
        - v2
    - name: pod-http-modify-header
      description: It injects pod-http-modify-header chaos in a Kubernetes pod.
      displayName: "Pod HTTP Modify Header"
      plan:
        - free
      supportedVersion:
        - v1
        - v2
    - name: pod-http-modify-body
      description: It injects pod-http-modify-body chaos in a Kubernetes pod.
      displayName: "Pod HTTP Modify Body"
      plan:
        - free
      supportedVersion:
        - v1
        - v2
    - name: pod-http-reset-peer
      description: It injects pod-http-reset-peer chaos in a Kubernetes pod.
      displayName: "Pod HTTP Reset Peer"
      plan:
        - free
      supportedVersion:
        - v1
        - v2
    - name: time-chaos
      description: It injects time-chaos in a Kubernetes pod.
      displayName: "Time Chaos"
      plan:
        - free
      supportedVersion:
        - v1
        - v2
    - name: pod-io-latency
      description: It injects pod-io-latency in a Kubernetes pod.
      displayName: "Pod IO Latency"
      plan:
        - enterprise
      supportedVersion:
        - v1
        - v2
    - name: pod-io-error
      description: It injects pod-io-error in a Kubernetes pod.
      displayName: "Pod IO Error"
      plan:
        - enterprise
      supportedVersion:
        - v1
        - v2
    - name: pod-io-attribute-override
      description: It injects pod-io-attribute-override in a Kubernetes pod.
      displayName: "Pod IO Attribute Override"
      plan:
        - enterprise
      supportedVersion:
        - v1
        - v2
    - name: pod-io-mistake
      description: It injects pod-io-mistake in a Kubernetes pod.
      displayName: "Pod IO Mistake"
      plan:
        - enterprise
      supportedVersion:
        - v1
        - v2
    - name: pod-api-latency
      description: It injects pod-api-latency in a Kubernetes pod.
      displayName: "Pod API Latency"
      plan:
        - enterprise
      supportedVersion:
        - v1
        - v2
    - name: pod-api-status-code
      description: It injects pod-api-status-code in a Kubernetes pod.
      displayName: "Pod API Status Code"
      plan:
        - enterprise
      supportedVersion:
        - v1
        - v2
    - name: pod-api-modify-header
      description: It injects pod-api-modify-header in a Kubernetes pod.
      displayName: "Pod API Modify Header"
      plan:
        - enterprise
      supportedVersion:
        - v1
        - v2
    - name: pod-api-modify-body
      description: It injects pod-api-modify-body in a Kubernetes pod.
      displayName: "Pod API Modify Body"
      plan:
        - enterprise
      supportedVersion:
        - v1
        - v2
    - name: pod-api-block
      description: It injects pod-api-block in a Kubernetes pod.
      displayName: "Pod API Block"
      plan:
        - enterprise
      supportedVersion:
        - v1
        - v2
    - name: pod-network-rate-limit
      description: It injects pod-network-rate-limit in a Kubernetes pod.
      displayName: "Pod Network Rate Limit"
      plan:
        - enterprise
      supportedVersion:
        - v1
        - v2
    - name: pod-jvm-method-exception
      description: It injects pod-jvm-method-exception in a Kubernetes pod.
      displayName: "Pod JVM Method Exception"
      plan:
        - enterprise
      supportedVersion:
        - v2
    - name: pod-jvm-method-latency
      description: It injects pod-jvm-method-latency in a Kubernetes pod.
      displayName: "Pod JVM Method Latency"
      plan:
        - enterprise
      supportedVersion:
        - v2
    - name: pod-jvm-modify-return
      description: It injects pod-jvm-modify-return in a Kubernetes pod.
      displayName: "Pod JVM Modify Return"
      plan:
        - enterprise
      supportedVersion:
        - v2
    - name: pod-jvm-cpu-stress
      description: It injects pod-jvm-cpu-stress in a Kubernetes pod.
      displayName: "Pod JVM CPU Stress"
      plan:
        - enterprise
      supportedVersion:
        - v2
    - name: pod-jvm-trigger-gc
      description: It injects pod-jvm-trigger-gc in a Kubernetes pod.
      displayName: "Pod JVM Trigger GC"
      plan:
        - enterprise
      supportedVersion:
        - v2
    - name: pod-jvm-sql-exception
      description: It injects pod-jvm-sql-exception in a Kubernetes pod.
      displayName: "Pod JVM SQL Exception"
      plan:
        - enterprise
      supportedVersion:
        - v2
    - name: pod-jvm-sql-latency
      description: It injects pod-jvm-sql-latency in a Kubernetes pod.
      displayName: "Pod JVM SQL Latency"
      plan:
        - enterprise
      supportedVersion:
        - v2
    - name: redis-cache-expire
      description: It injects redis-cache-expire for a Redis instance.
      displayName: "Redis Cache Expire"
      plan:
        - enterprise
      supportedVersion:
        - v2
    - name: redis-cache-penetration
      description: It injects redis-cache-penetration for a Redis instance.
      displayName: "Redis Cache Penetration"
      plan:
        - enterprise
      supportedVersion:
        - v2
    - name: redis-cache-limit
      description: It injects redis-cache-limit for a Redis instance.
      displayName: "Redis Cache Limit"
      plan:
        - enterprise
      supportedVersion:
        - v2
  keywords:
    - Kubernetes
    - Azure
    - AWS
    - GCP
  minKubeVersion: 1.12.0
  links:
    - name: Kubernetes Website
      url: https://kubernetes.io
    - name: Source Code
      url: https://github.com/kubernetes/kubernetes
    - name: Kubernetes Slack
      url: https://slack.kubernetes.io/
    - name: Documentation
      url: https://litmuschaos.github.io/litmus/experiments/categories/contents/#kubernetes
  icon:
    - url: https://raw.githubusercontent.com/litmuschaos/charthub.litmuschaos.io/master/public/litmus.ico
      mediatype: image/png
