---
apiVersion: litmuschaos.io/v1alpha1
kind: ChaosEngine
metadata:
  name: pod-autoscaler
  namespace: default
  labels:
    name: pod-autoscaler
    app.kubernetes.io/part-of: litmus
    app.kubernetes.io/component: experiment-job
    app.kubernetes.io/version: ci
spec:
  # It can be active/stop
  engineState: "active"
  terminationGracePeriodSeconds: 30
  #ex. values: ns1:name=percona,ns2:run=nginx
  auxiliaryAppInfo: ""
  appinfo:
    appns: ""
    applabel: ""
    appkind: ""
  chaosServiceAccount: pod-autoscaler-sa
  experiments:
    - name: pod-autoscaler
      image: artifactory.sdlc.ctl.gcp.db.com/dkr-public-local/com/db/chaos-hce/thirdparty/harness/chaos-go-runner:1.41.0
      imagePullPolicy: Always
      args:
        - -c
        - ./experiments -name pod-autoscaler
      command:
        - /bin/bash
      spec:
        components:
          env:
            - name: TOTAL_CHAOS_DURATION
              value: "60"

            # Period to wait before and after injection of chaos in sec
            - name: RAMP_TIME
              value: ""

            # Number of replicas to scale
            - name: REPLICA_COUNT
              value: "5"

            - name: DEFAULT_HEALTH_CHECK
              value: "false"
