---
apiVersion: litmuschaos.io/v1alpha1
kind: K8sFault
metadata:
  name: pod-autoscaler
spec:
  definition:
    targets:
      appinfo:
        applabel: ""
        appkind: ""
        appns: ""
    chaos:
      experiment: pod-autoscaler
      serviceAccountName: litmus-admin
      image: artifactory.sdlc.ctl.gcp.db.com/dkr-public-local/dkr-io/harness/chaos-ddcr-faults:1.54.0
      imagePullPolicy: Always
      env:
        - name: TOTAL_CHAOS_DURATION
          value: "60" # in seconds

        # Number of replicas to scale
        - name: REPLICA_COUNT
          value: "5"

        ## Period to wait before and after injection of chaos in sec
        - name: RAMP_TIME
          value: ""
