---
apiVersion: litmuschaos.io/v1alpha1
kind: ChaosEngine
metadata:
  name: pod-network-rate-limit
  namespace: default
  labels:
    name: pod-network-rate-limit
    app.kubernetes.io/part-of: litmus
    app.kubernetes.io/component: experiment-job
    app.kubernetes.io/runtime-api-usage: "true"
    app.kubernetes.io/version: ci
spec:
  # It can be active/stop
  engineState: "active"
  terminationGracePeriodSeconds: 30
  appinfo:
    appns: ""
    # FYI, To see app label, apply kubectl get pods --show-labels
    applabel: ""
    appkind: ""
  chaosServiceAccount: pod-network-rate-limit-sa
  experiments:
    - name: pod-network-rate-limit
      image: artifactory.sdlc.ctl.gcp.db.com/dkr-public-local/com/db/chaos-hce/thirdparty/harness/chaos-go-runner:1.41.0
      imagePullPolicy: Always
      args:
        - -c
        - ./experiments -name pod-network-rate-limit
      command:
        - /bin/bash
      spec:
        components:
          env:
            - name: TARGET_CONTAINER
              value: ""

            # provide lib image
            - name: LIB_IMAGE
              value: artifactory.sdlc.ctl.gcp.db.com/dkr-public-local/com/db/chaos-hce/thirdparty/harness/chaos-go-runner:1.41.0

            - name: NETWORK_INTERFACE
              value: "eth0"

            - name: NETWORK_BANDWIDTH
              value: "1mbit"

            - name: BURST
              value: "32kb"

            - name: LIMIT
              value: "2mb"

            - name: MIN_BURST
              value: ""

            - name: PEAK_RATE
              value: ""

            - name: TOTAL_CHAOS_DURATION
              value: "60" # in seconds

            # time period to wait before and after injection of chaos in sec
            - name: RAMP_TIME
              value: ""

            ## percentage of total pods to target
            - name: PODS_AFFECTED_PERC
              value: ""

            - name: TARGET_PODS
              value: ""

            # To select pods on specific node(s)
            - name: NODE_LABEL
              value: ""

            # provide the name of container runtime
            # it supports docker, containerd, crio
            - name: CONTAINER_RUNTIME
              value: "containerd"

            # provide the destination ips
            # chaos injection will be triggered for these destination ips
            - name: DESTINATION_IPS
              value: ""

            # provide the destination hosts
            # chaos injection will be triggered for these destination hosts
            - name: DESTINATION_HOSTS
              value: ""

            # provide the socket file path
            - name: SOCKET_PATH
              value: "/run/containerd/containerd.sock"

            ## it defines the sequence of chaos execution for multiple target pods
            ## supported values: serial, parallel
            - name: SEQUENCE
              value: "parallel"
