---
apiVersion: litmuschaos.io/v1alpha1
kind: ChaosEngine
metadata:
  name: vmware-windows-network-duplication
  namespace: default
  labels:
    name: vmware-windows-network-duplication
    app.kubernetes.io/part-of: litmus
    app.kubernetes.io/component: experiment-job
    app.kubernetes.io/version: ci
spec:
  engineState: "active"
  terminationGracePeriodSeconds: 30
  chaosServiceAccount: litmus-admin
  experiments:
    - name: vmware-windows-network-duplication
      image: artifactory.sdlc.ctl.gcp.db.com/dkr-public-local/dkr-io/harness/chaos-go-runner:1.54.0
      imagePullPolicy: Always
      args:
        - -c
        - ./experiments -name vmware-windows-network-duplication
      command:
        - /bin/bash
      spec:
        components:
          env:
            - name: TOTAL_CHAOS_DURATION
              value: "60"

            - name: VM_NAME
              value: ""

            - name: VM_USER_NAME
              value: ""

            - name: VM_PASSWORD
              value: ""

            - name: DESTINATION_HOSTS
              value: ""

            - name: DESTINATION_IPS
              value: ""

            - name: NETWORK_PACKET_DUPLICATION_PERCENTAGE
              value: "100"

            - name: PATH_OF_CLUSMY
              value: ""

            - name: RAMP_TIME
              value: ""

            - name: SEQUENCE
              value: "parallel"

            - name: GOVC_URL
              valueFrom:
                secretKeyRef:
                  name: vcenter-secret
                  key: VCENTERSERVER

            - name: GOVC_USERNAME
              valueFrom:
                secretKeyRef:
                  name: vcenter-secret
                  key: VCENTERUSER

            - name: GOVC_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: vcenter-secret
                  key: VCENTERPASS

            - name: GOVC_INSECURE
              value: "true"
