---
apiVersion: litmuschaos.io/v1alpha1
kind: ChaosEngine
metadata:
  name: vmware-http-reset-peer
  namespace: default
  labels:
    name: vmware-http-reset-peer
    app.kubernetes.io/part-of: litmus
    app.kubernetes.io/component: experiment-job
    app.kubernetes.io/version: ci
spec:
  # It can be active/stop
  engineState: "active"
  terminationGracePeriodSeconds: 30
  chaosServiceAccount: litms-admin
  experiments:
    - name: vmware-http-reset-peer
      image: artifactory.sdlc.ctl.gcp.db.com/dkr-public-local/dkr-io/harness/chaos-go-runner:1.41.0
      imagePullPolicy: Always
      args:
        - -c
        - ./experiments -name vmware-http-reset-peer
      command:
        - /bin/bash
      spec:
        components:
          env:
            # provide lib image
            - name: LIB_IMAGE
              value: artifactory.sdlc.ctl.gcp.db.com/dkr-public-local/dkr-io/harness/chaos-go-runner:1.41.0

            # reset timeout specifies after how much duration to reset the connection
            - name: RESET_TIMEOUT
              value: "0" #in ms

            # port of the target service
            - name: TARGET_SERVICE_PORT
              value: "80"

            # port on which the proxy will listen
            - name: PROXY_PORT
              value: "8080"

            # network interface on which the proxy will listen
            - name: NETWORK_INTERFACE
              value: "ens160"

            - name: VM_NAME
              value: ""

            - name: VM_USER_NAME
              value: ""

            - name: VM_PASSWORD
              value: ""

            - name: TOTAL_CHAOS_DURATION
              value: "60"

            - name: CHAOS_INTERVAL
              value: "60"

            # Time period to wait before and after injection of chaos in sec
            - name: RAMP_TIME
              value: ''

            ## it defines the sequence of chaos execution for multiple target vms
            ## supported values: serial, parallel
            - name: SEQUENCE
              value: "parallel"

            - name: DEFAULT_HEALTH_CHECK
              value: "false"

            - name: GOVC_URL
              valueFrom:
                secretKeyRef:
                  name: vcenter-secret
                  key: VCENTERSERVER

            - name: GOVC_USERNAME
              valueFrom:
                secretKeyRef:
                  name: vcenter-secret
                  key: VCENTERUSER

            - name: GOVC_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: vcenter-secret
                  key: VCENTERPASS

            - name: GOVC_INSECURE
              value: "true"
