---
apiVersion: litmuchaos.io/v1alpha1
kind: K8sFault
metadata:
  name: ecs-container-io-stress
spec:
  definition:
    chaos:
      experiment: ecs-container-io-stress
      serviceAccountName: litmus-admin
      image: artifactory.sdlc.ctl.gcp.db.com/dkr-public-local/dkr-io/harness/chaos-ddcr-faults:1.54.0
      imagePullPolicy: Always
      env:
        - name: TOTAL_CHAOS_DURATION
          value: "60"

        - name: RAMP_TIME
          value: ""

        - name: CLUSTER_NAME
          value: ""

        - name: SERVICE_NAME
          value: ""

        - name: REGION
          value: ""

        # set file-system utilization bytes in GB
        - name: FILESYSTEM_UTILIZATION_BYTES
          value: "1"

        - name: FILESYSTEM_UTILIZATION_PERCENTAGE
          value: "0"

        - name: VOLUME_MOUNT_PATH
          value: "/tmp"

        - name: NUMBER_OF_WORKERS
          value: "1"

        - name: INSTALL_DEPENDENCIES
          value: "true"

        - name: AWS_SHARED_CREDENTIALS_FILE
          value: "/tmp/cloud_config.yml"

        - name: DEFAULT_HEALTH_CHECK
          value: "false"

        - name: SEQUENCE
          value: "parallel"
