---
apiVersion: litmuschaos.io/v1alpha1
kind: ChaosEngine
metadata:
  name: azure-disk-loss
  labels:
    name: azure-disk-loss
    app.kubernetes.io/part-of: litmus
    app.kubernetes.io/component: experiment-job
    app.kubernetes.io/version: ci
spec:
  # It can be active/stop
  engineState: "active"
  terminationGracePeriodSeconds: 30
  chaosServiceAccount: litmus-admin
  experiments:
    - name: azure-disk-loss
      image: artifactory.sdlc.ctl.gcp.db.com/dkr-public-local/com/db/chaos-hce/thirdparty/harness/chaos-go-runner:1.38.2
      imagePullPolicy: Always
      args:
        - -c
        - ./experiments -name azure-disk-loss
      command:
        - /bin/bash
      spec:
        components:
          env:
            - name: TOTAL_CHAOS_DURATION
              value: "30"

            - name: CHAOS_INTERVAL
              value: "30"

            # Period to wait before and after injection of chaos in sec
            - name: RAMP_TIME
              value: ""

            # provide the resource group of the instance
            - name: RESOURCE_GROUP
              value: ""

            # accepts enable/disable, default is disable
            - name: SCALE_SET
              value: ""

            # provide the virtual disk names (comma separated if multiple)
            - name: VIRTUAL_DISK_NAMES
              value: ""

            # provide the sequence type for the run. Options: serial/parallel
            - name: SEQUENCE
              value: "parallel"

            # provide the path to aks credentials mounted from secret
            - name: AZURE_AUTH_LOCATION
              value: "/tmp/azure.auth"

            - name: DEFAULT_HEALTH_CHECK
              value: "false"
          secrets:
            - name: cloud-secret
              mountPath: /tmp/
        probe:
          - name: healthcheck
            type: cmdProbe
            mode: Edge
            runProperties:
              probeTimeout: 5s
              retry: 0
              interval: 1s
              stopOnFailure: false
            cmdProbe/inputs:
              command: ./healthcheck -name azure-disk-loss
              source:
                image: artifactory.sdlc.ctl.gcp.db.com/dkr-public-local/com/db/chaos-hce/thirdparty/harness/chaos-go-runner:1.38.2
                inheritInputs: true
              comparator:
                type: string
                criteria: contains
                value: "[P000]"
