---
apiVersion: litmuschaos.io/v1alpha1
kind: ChaosEngine
metadata:
  name: ecs-task-scale
  namespace: default
  labels:
    name: ecs-task-scale
    app.kubernetes.io/part-of: litmus
    app.kubernetes.io/component: experiment-job
    app.kubernetes.io/version: ci
    app.kubernetes.io/enableAWSAccessViaSecrets: disable
spec:
  engineState: "active"
  terminationGracePeriodSeconds: 30
  chaosServiceAccount: ecs-task-scale-sa
  experiments:
    - name: ecs-task-scale
      image: artifactory.sdlc.ctl.gcp.db.com/dkr-public-local/dkr-io/harness/chaos-go-runner:1.41.0
      imagePullPolicy: Always
      args:
        - -c
        - ./experiments -name ecs-task-scale
      command:
        - /bin/bash
      spec:
        components:
          env:
            - name: TOTAL_CHAOS_DURATION
              value: "30"

            - name: RAMP_TIME
              value: ""

            - name: CLUSTER_NAME
              value: ""

            - name: SERVICE_NAMES
              value: ""

            - name: REGION
              value: ""

            - name: REPLICAS
              value: "5"

            - name: AWS_SHARED_CREDENTIALS_FILE
              value: "/tmp/cloud_config.yml"
          projectedVolumes:
            - name: aws-iam-token
              mountPath: /var/run/secrets/eks.amazonaws.com/serviceaccount
              readOnly: true
              projected:
                defaultMode: 420
                sources:
                  - serviceAccountToken:
                      audience: sts.amazonaws.com
                      expirationSeconds: 86400
                      path: token
