---
apiVersion: litmuchaos.io/v1alpha1
kind: MachineFault
metadata:
  name: windows-network-latency
  labels:
    name: network-latency
spec:
  infraType: windows
  env:
    - name: NETWORK_LATENCY
      value: "2000"
    - name: DESTINATION_HOSTS
      value: ""
    - name: DESTINATION_IPS
      value: ""
    - name: DURATION
      value: "60s"
    - name: RAMP_TIME
      value: ""
