---
apiVersion: litmuschaos.io/v1alpha1
kind: ChaosEngine
metadata:
  name: azure-app-access-restrict
  namespace: default
  labels:
    name: azure-app-access-restrict
    app.kubernetes.io/part-of: chaosnative
    app.kubernetes.io/component: experiment-job
    app.kubernetes.io/version: ci
spec:
  engineState: "active"
  terminationGracePeriodSeconds: 30
  chaosServiceAccount: litmus-admin
  experiments:
    - name: azure-app-access-restrict
      image: artifactory.sdlc.ctl.gcp.db.com/dkr-public-local/dkr-io/harness/chaos-go-runner:1.54.0
      imagePullPolicy: Always
      args:
        - -c
        - ./experiments -name azure-app-access-restrict
      command:
        - /bin/bash
      spec:
        components:
          env:
            - name: TOTAL_CHAOS_DURATION
              value: "60"
            - name: CHAOS_INTERVAL
              value: "60"
            - name: RAMP_TIME
              value: ""
            - name: AZURE_WEB_APP_NAMES
              value: ""
            - name: RESOURCE_GROUP
              value: ""
            - name: RULE_NAME
              value: "litmus-rule"
            - name: ACTION
              value: Deny
            - name: PRIORITY
              value: "300"
            - name: IP_ADDRESS_BLOCK
              value: 0.0.0.0/0
            - name: AZURE_AUTH_LOCATION
              value: /tmp/azure.auth
            - name: DEFAULT_HEALTH_CHECK
              value: "false"
          secrets:
            - name: cloud-secret
              mountPath: /tmp/
