---
apiVersion: litmuschaos.io/v1alpha1
kind: ChaosEngine
metadata:
  name: ecs-network-restrict
  namespace: default
  labels:
    name: ecs-network-restrict
    app.kubernetes.io/part-of: litmus
    app.kubernetes.io/component: experiment-job
    app.kubernetes.io/version: ci
    app.kubernetes.io/enableAWSAccessViaSecrets: disable
spec:
  engineState: "active"
  terminationGracePeriodSeconds: 30
  chaosServiceAccount: ecs-network-restrict-sa
  experiments:
    - name: ecs-network-restrict
      image: artifactory.sdlc.ctl.gcp.db.com/dkr-public-local/dkr-io/harness/chaos-go-runner:1.41.0
      imagePullPolicy: Always
      args:
        - -c
        - ./experiments -name ecs-network-restrict
      command:
        - /bin/bash
      spec:
        components:
          env:
            - name: TOTAL_CHAOS_DURATION
              value: "30"

            - name: CHAOS_INTERVAL
              value: "30"

            - name: RAMP_TIME
              value: ""

            - name: CLUSTER_NAME
              value: ""

            - name: SERVICE_NAMES
              value: ""

            - name: REGION
              value: ""

            - name: IP_ADDRESS
              value: ""

            - name: PROTOCOL
              value: "tcp"

            - name: FROM_PORT
              value: "80"

            - name: TO_PORT
              value: "80"

            - name: RULE_TYPE
              value: "outbound"

            - name: RULE_MODE
              value: "remove"

            - name: SEQUENCE
              value: "parallel"

            - name: AWS_SHARED_CREDENTIALS_FILE
              value: "/tmp/cloud_config.yml"
          projectedVolumes:
            - name: aws-iam-token
              mountPath: /var/run/secrets/eks.amazonaws.com/serviceaccount
              readOnly: true
              projected:
                defaultMode: 420
                sources:
                  - serviceAccountToken:
                      audience: sts.amazonaws.com
                      expirationSeconds: 86400
                      path: token
