---
apiVersion: litmuchaos.io/v1alpha1
kind: ChartServiceVersion
metadata:
  name: windows
  annotations:
    categories: Windows
    chartDescription: Injects chaos in windows VM
    executionPlane: "windows"
spec:
  displayName: Windows
  categoryDescription: >
    It contains chaos to disrupt state of a windows VM
  faults:
    - name: windows-cpu-stress
      description: It injects cpu stress to a windows VM.
      displayName: "Windows CPU Stress"
      plan:
        - team
    - name: windows-memory-stress
      description: It injects memory stress to a windows VM.
      displayName: "Windows Memory Stress"
      plan:
        - team
    - name: windows-blackhole-chaos
      description: It injects network loss to a windows VM.
      displayName: "Windows Blackhole Chaos"
      plan:
        - team
    - name: windows-network-latency
      description: It injects network latency to a windows VM.
      displayName: "Windows Network Latency"
      plan:
        - team
    - name: windows-network-loss
      description: It injects network loss to a windows VM.
      displayName: "Windows Network Loss"
      plan:
        - team
    - name: windows-network-corruption
      description: It injects network corruption to a windows VM.
      displayName: "Windows Network Corruption"
      plan:
        - team
    - name: windows-network-duplication
      description: It injects network duplication to a windows VM.
      displayName: "Windows Network Duplication"
      plan:
        - team
    - name: windows-process-kill
      description: It injects process kill to a windows VM.
      displayName: "Windows Process Kill"
      plan:
        - team
    - name: windows-disk-stress
      description: It injects disk stress to a windows VM.
      displayName: "Windows Disk Stress"
      plan:
        - team
  keywords:
    - Windows
    - CPU
    - Memory
    - Network
    - GCP
    - Azure
    - Disk
