---
apiVersion: litmuschaos.io/v1alpha1
kind: ChartServiceVersion
metadata:
  createdAt: 2022-11-29T16:42:19Z
  name: lambda-function-layer-detach
  version: 0.1.0
  annotations:
    categories: AWS
    vendor: Harness
spec:
  displayName: Lambda Function Layer Detach
  categoryDescription: |
    This fault causes layers of a lambda function to detach for a certain chaos period
  keywords:
    - AWS
  plan:
    - enterprise
  platforms:
    - AWS
  experiments:
    - aws-lambda-function-layer-detach
  chaosType: infra
  labels:
    app.kubernetes.io/component: chartserviceversion
    app.kubernetes.io/version: ci
  links:
    - name: Documentation
      url: https://docs.harness.io/category/kl0mxwpfw1-hce-category
  icon:
    - url:
      mediatype: ""
