---
apiVersion: litmuschaos.io/v1alpha1
kind: ChaosEngine
metadata:
  name: ec2-cpu-hog
  namespace: default
  labels:
    name: ec2-cpu-hog
    app.kubernetes.io/part-of: litmus
    app.kubernetes.io/component: experiment-job
    app.kubernetes.io/version: ci
    app.kubernetes.io/enableAWSAccessViaSecrets: disable
spec:
  engineState: "active"
  terminationGracePeriodSeconds: 30
  chaosServiceAccount: litmus-admin
  experiments:
    - name: ec2-cpu-hog
      image: artifactory.sdlc.ctl.gcp.db.com/dkr-public-local/dkr-io/harness/chaos-go-runner:1.41.0
      imagePullPolicy: Always
      args:
        - -c
        - ./experiments -name ec2-cpu-hog
      command:
        - /bin/bash
      spec:
        components:
          env:
            - name: TOTAL_CHAOS_DURATION
              value: "30"
            - name: RAMP_TIME
              value: ""
            - name: EC2_INSTANCE_ID
              value: ""
            - name: CPU_CORE
              value: "0"
            - name: CPU_LOAD
              value: "100"
            - name: DEFAULT_HEALTH_CHECK
              value: "false"
            - name: AWS_SHARED_CREDENTIALS_FILE
              value: /tmp/cloud_config.yml
            - name: MACHINE
              value: "linux"
            - name: SEQUENCE
              value: "parallel"
          projectedVolumes:
            - name: aws-iam-token
              mountPath: /var/run/secrets/eks.amazonaws.com/serviceaccount
              readOnly: true
              projected:
                defaultMode: 420
                sources:
                  - serviceAccountToken:
                      audience: sts.amazonaws.com
                      expirationSeconds: 86400
                      path: token
