---
apiVersion: litmuschaos.io/v1alpha1
kind: ChaosEngine
metadata:
  name: resource-access-restrict
  namespace: default
  labels:
    name: resource-access-restrict
    app.kubernetes.io/part-of: litmus
    app.kubernetes.io/component: experiment-job
    app.kubernetes.io/version: ci
    app.kubernetes.io/enableAWSAccessViaSecrets: disable
spec:
  engineState: "active"
  terminationGracePeriodSeconds: 30
  chaosServiceAccount: resource-access-restrict-sa
  experiments:
    - name: resource-access-restrict
      image: artifactory.sdlc.ctl.gcp.db.com/dkr-public-local/dkr-io/harness/chaos-go-runner:1.41.0
      imagePullPolicy: Always
      args:
        - -c
        - ./experiments -name resource-access-restrict
      command:
        - /bin/bash
      spec:
        components:
          env:
            - name: TOTAL_CHAOS_DURATION
              value: "30"

            - name: CHAOS_INTERVAL
              value: "30"

            - name: RAMP_TIME
              value: ""

            - name: SECURITY_GROUP_IDS
              value: ""

            - name: RULE_TYPE
              value: "outbound"

            - name: REGION
              value: ""

            - name: AWS_SHARED_CREDENTIALS_FILE
              value: "/tmp/cloud_config.yml"
          projectedVolumes:
            - name: aws-iam-token
              mountPath: /var/run/secrets/eks.amazonaws.com/serviceaccount
              readOnly: true
              projected:
                defaultMode: 420
                sources:
                  - serviceAccountToken:
                      audience: sts.amazonaws.com
                      expirationSeconds: 86400
                      path: token
