---
apiVersion: litmuschaos.io/v1alpha1
kind: ChaosEngine
metadata:
  name: vmware-windows-process-kill
  namespace: default
  labels:
    name: vmware-windows-process-kill
    app.kubernetes.io/part-of: litmus
    app.kubernetes.io/component: experiment-job
    app.kubernetes.io/version: ci
spec:
  engineState: "active"
  terminationGracePeriodSeconds: 30
  chaosServiceAccount: litmus-admin
  experiments:
    - name: vmware-process-kill
      image: artifactory.sdlc.ctl.gcp.db.com/dkr-public-local/com/db/chaos-hce/thirdparty/harness/chaos-go-runner:1.41.0
      imagePullPolicy: Always
      args:
        - -c
        - ./experiments -name vmware-windows-process-kill
      command:
        - /bin/bash
      spec:
        components:
          env:
            - name: TOTAL_CHAOS_DURATION
              value: "60"

            - name: VM_NAME
              value: ""

            - name: VM_USER_NAME
              value: ""

            - name: VM_PASSWORD
              value: ""

            - name: PROCESS_IDS
              value: ""

            - name: PROCESS_NAMES
              value: ""

            - name: FORCE
              value: "disable"

            - name: RAMP_TIME
              value: ""

            - name: SEQUENCE
              value: "parallel"

            - name: GOVC_URL
              valueFrom:
                secretKeyRef:
                  name: vcenter-secret
                  key: VCENTERSERVER

            - name: GOVC_USERNAME
              valueFrom:
                secretKeyRef:
                  name: vcenter-secret
                  key: VCENTERUSER

            - name: GOVC_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: vcenter-secret
                  key: VCENTERPASS

            - name: GOVC_INSECURE
              value: "true"
