---
apiVersion: litmuschaos.io/v1alpha1
kind: ChaosEngine
metadata:
  name: locust-loadgen-chaos
  namespace: default
  labels:
    name: locust-loadgen-chaos
    app.kubernetes.io/part-of: litmus
    app.kubernetes.io/component: experiment-job
    app.kubernetes.io/version: ci
spec:
  engineState: "active"
  terminationGracePeriodSeconds: 30
  chaosServiceAccount: litmus-admin
  experiments:
    - name: locust-loadgen-chaos
      image: artifactory.sdlc.ctl.gcp.db.com/dkr-public-local/com/db/chaos-hce/thirdparty/harness/chaos-go-runner:1.41.0
      imagePullPolicy: Always
      args:
        - -c
        - ./experiments -name locust-load-generator
      command:
        - /bin/bash
      spec:
        components:
          env:
            - name: TOTAL_CHAOS_DURATION
              value: "60"
            - name: CHAOS_INTERVAL
              value: "60"
            - name: USERS
              value: "50"
            - name: SPAWN_RATE
              value: "50"
            - name: HOST
              value: https://google.com
            - name: LOAD_TYPE
              value: load
            - name: GRANT_TYPE
              value: client_credentials
            - name: NODE_NAMES
              value: ""
            - name: REPLICA
              value: "1"
            - name: CONFIG_MAP_FILE
              value: /tmp/load/config.py
            - name: RAMP_TIME
              value: ""
            - name: LOAD_IMAGE
              value: chaosnative/locust-loadgen:latest
          configMaps:
            - name: load
              mountPath: /tmp/load
