---
apiVersion: litmuschaos.io/v1alpha1
description:
  message: |
    It injects the load chaos on the given target hosts for a specific chaos duration
kind: ChaosExperiment
metadata:
  name: locust-loadgen-chaos
  labels:
    name: locust-loadgen-chaos
    app.kubernetes.io/part-of: litmus
    app.kubernetes.io/component: chaosexperiment
    app.kubernetes.io/version: ci
spec:
  definition:
    scope: Cluster
    permissions:
      - apiGroups:
          - ""
          - batch
          - litmuschaos.io
        resources:
          - jobs
          - pods
          - events
          - pods/log
          - pods/exec
          - secrets
          - chaosengines
          - chaosexperiments
          - chaosresults
        verbs:
          - create
          - list
          - get
          - patch
          - update
          - delete
    image: artifactory.sdlc.ctl.gcp.db.com/dkr-public-local/dkr-io/harness/chaos-go-runner:1.41.0
    imagePullPolicy: Always
    args:
      - -c
      - ./experiments -name locust-load-generator
    command:
      - /bin/bash
    env:
      - name: TOTAL_CHAOS_DURATION
        value: "60"
      - name: CHAOS_INTERVAL
        value: "60"
      - name: USERS
        value: "300"
      - name: SPAWN_RATE
        value: "300"
      - name: HOST
        value: https://google.com
      - name: LOAD_TYPE
        value: load
      - name: GRANT_TYPE
        value: client_credentials
      - name: NODE_NAMES
        value: ""
      - name: REPLICA
        value: "3"
      - name: CONFIG_MAP_FILE
        value: /tmp/load/config.py
      - name: RAMP_TIME
        value: ""
      - name: LOAD_IMAGE
        value: chaosnative/locust-loadgen:latest
    labels:
      name: locust-loadgen-chaos
      app.kubernetes.io/part-of: litmus
      app.kubernetes.io/component: experiment-job
      app.kubernetes.io/version: ci
    configMaps:
      - name: load
        mountPath: /tmp/load
