---
name: Copy-ChaosHub-Pipeline
on:
  workflow_dispatch:
    inputs:
      HceNamespace:
        type: boolean
        default: ""
      ProjectID:
        default: ""

jobs:
  COPY_CHAOSHUB:
    runs-on: ubuntu-latest
    env:
      HCE_NAMESPACE: ${{ github.event.inputs.HceNamespace }}
      PROJECT_ID: ${{ github.event.inputs.ProjectID }}
    steps:
      - uses: actions/checkout@v2

      - name: Authenticate Google Cloud SDK
        if: always()
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - id: 'get-credentials'
        uses: 'google-github-actions/get-gke-credentials@v0'
        with:
          cluster_name: 'vedant-cluster'
          location: 'us-east5-a'

      - name: Adding Chaoshub 
        run: |
          pod_name=$(kubectl get pods --selector="app.kubernetes.io/component=hce-server" --output=jsonpath={.items..metadata.name} -n ${HCE_NAMESPACE})
          kubectl cp ./chaos-hub/. ${HCE_NAMESPACE}/${pod_name}:/tmp/version/${PROJECT_ID}/"Litmus ChaosHub" -c graphql-server
        env:
          


