---
name: GKE-Agent-Plane-Patch-Pipeline
on:
  workflow_dispatch:
    inputs:
      UpdateConfigMap:
        type: boolean
        default: ""
      HceAccessUrl:
        default: ""
      patchImagePullSecret:
        type: boolean
        default: ""

jobs:
  IMAGE_PULL_SECRET_PATCH_JOB:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.patchImagePullSecret == 'true' }}
    steps:
      - uses: actions/checkout@v2

      - name: Authenticate Google Cloud SDK
        if: always()
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - id: 'get-credentials'
        uses: 'google-github-actions/get-gke-credentials@v0'
        with:
          cluster_name: 'vedant-cluster'
          location: 'us-east1-d'

      - name: Adding ImagePullSecrets in Execution plane components
        run: |
          deployments=( chaos-exporter chaos-operator-ce event-tracker subscriber workflow-controller )
          for i in "${deployments[@]}"
          do
            kubectl patch deploy $i -p '{ "spec": { "template": { "spec": { "imagePullSecrets": [{"name": "regcred"}] } } } }' -n litmus
          done

  ACCESS_URL_UPDATE:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.UpdateConfigMap == 'true' }}
    steps:
      - uses: actions/checkout@v2

      - name: Authenticate Google Cloud SDK
        if: always()
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - id: 'get-credentials'
        uses: 'google-github-actions/get-gke-credentials@v0'
        with:
          cluster_name: 'vedant-cluster'
          location: 'us-east1-d'

      - name: Updating the configMap for accessing Server through Gateway URL
        run: |
          kubectl patch configmap/agent-config -n litmus --type merge -p '{"data":{"SERVER_ADDR": "'${ACCESS_URL}'"}}'
          pod_name=$(kubectl get pods --selector="app=subscriber" --output=jsonpath={.items..metadata.name} -n litmus)
          kubectl delete pod $pod_name -n litmus
        env:
          ACCESS_URL: ${{ github.event.inputs.HceAccessUrl }}

