---
apiVersion: litmuchaos.io/v1alpha1
kind: ChartServiceVersion
metadata:
  createdAt: 2023-03-19T10:28:08Z
  name: redis-sentinel-stop
  version: 0.1.0
  annotations:
    categories: Linux
    vendor: Harness
spec:
  displayName: redis-sentinel-stop
  categoryDescription: |
    This fault causes Redis sentinel server to be stopped.
    - Stops and then starts redis sentinel.
    - Determines the resiliency of Redis dependent apps against redis unavailability.
  keywords:
    - Linux
    - Redis
    - Sentinel
    - Stop
  plan:
    - team
  maturity: alpha
  labels:
    app.kubernetes.io/component: chartserviceversion
    app.kubernetes.io/version: ci
  links:
    - name: Documentation
      url: https://developer.harness.io/docs/chaos-engineering/technical-reference/chaos-faults/linux/
  icon:
    - url:
      mediatype: ""
  experiments:
    - redis-sentinel-stop
