apiVersion: litmuschaos.io/v1alpha1
kind: ChaosEngine
metadata:
  name: nginx-chaos
  namespace: default
spec:
  components:
    runner:
      # secret name for the runner image, if using private registry
      imagePullSecrets:
      - name: regcred
      runnerAnnotations:
        sidecar.istio.io/inject: "false"
  # It can be active/stop
  engineState: 'active'
  auxiliaryAppInfo: ''
  chaosServiceAccount: docker-service-kill-sa
  experiments:
    - name: docker-service-kill
      spec:
          components:
            # secret name for the experiment image, if using private registry
            experimentImagePullSecrets:
            - name: regcred
            experimentAnnotations:
              sidecar.istio.io/inject: "false"
        # nodeSelector: 
        #   # provide the node labels
        #   kubernetes.io/hostname: 'node02'
          env:
            - name: TOTAL_CHAOS_DURATION
              value: '90' # in seconds
              
            - name: TARGET_NODE
              value: ''