---
apiVersion: litmuschaos.io/v1alpha1
kind: ChartServiceVersion
metadata:
  createdAt: 2025-01-28T16:32:08Z
  name: lambda-modify-response-body
  version: 0.1.0
  annotations:
    categories: AWS
    vendor: Harness
spec:
  displayName: Lambda Modify Respond Body
  categoryDescription: |
    This fault causes runtime injection to modify the response body of a lambda function.
  keywords:
    - AWS
  plan:
    - enterprise
  platforms:
    - AWS
  experiments:
    - aws-lambda-modify-response-body
  chaosType: infra
  labels:
    app.kubernetes.io/component: chartserviceversion
    app.kubernetes.io/version: ci
  links:
    - name: Documentation
      url: https://docs.harness.io/category/kl0mxwpfw1-hce-category
  icon:
    - url:
      mediatype: ""
