---
apiVersion: litmuchaos.io/v1alpha1
kind: ChartServiceVersion
metadata:
  createdAt: 2023-03-19T10:28:08Z
  name: linux-api-status-code
  version: 0.1.0
  annotations:
    categories: Linux
    vendor: Harness
spec:
  displayName: linux-api-status-code
  categoryDescription: |
    This fault injects API status code into a Linux machine.
    - Causes the status code of an API call to be modified to a given value
  keywords:
    - Linux
    - API
    - Status code
  plan:
    - team
  maturity: alpha
  labels:
    app.kubernetes.io/component: chartserviceversion
    app.kubernetes.io/version: ci
  links:
    - name: Documentation
      url: https://developer.harness.io/docs/chaos-engineering/technical-reference/chaos-faults/linux/
  icon:
    - url:
      mediatype: ""
  experiments:
    - linux-api-status-code
