---
apiVersion: litmuschaos.io/v1alpha1
kind: ChaosEngine
metadata:
  name: ec2-container-http-status-code
  namespace: default
  labels:
    name: ec2-container-http-status-code
    app.kubernetes.io/part-of: litmus
    app.kubernetes.io/component: experiment-job
    app.kubernetes.io/version: ci
    app.kubernetes.io/enableAWSAccessViaSecrets: disable
spec:
  engineState: "active"
  terminationGracePeriodSeconds: 30
  chaosServiceAccount: litmus-admin
  experiments:
    - name: ec2-container-http-status-code
      image: artifactory.sdlc.ctl.gcp.db.com/dkr-public-local/com/db/chaos-hce/thirdparty/harness/chaos-go-runner:1.38.2
      imagePullPolicy: Always
      args:
        - -c
        - ./experiments -name ec2-container-http-status-code
      command:
        - /bin/bash
      spec:
        components:
          env:
            - name: TOTAL_CHAOS_DURATION
              value: "60"
            - name: CLUSTER_NAME
              value: ""
            - name: SERVICE_NAME
              value: ""
            - name: RAMP_TIME
              value: ""
            - name: REGION
              value: ""
            - name: TASK_REPLICA_ID
              value: ""
            - name: TASK_REPLICA_AFFECTED_PERC
              value: "100"
            - name: NETWORK_INTERFACE
              value: eth0
            - name: TARGET_SERVICE_PORT
              value: "80"
            - name: STATUS_CODE
              value: "503"
            - name: MODIFY_RESPONSE_BODY
              value: "true"
            - name: SEQUENCE
              value: "parallel"
            - name: PROXY_PORT
              value: "20000"
            - name: AWS_SHARED_CREDENTIALS_FILE
              value: /tmp/cloud_config.yml
        probe:
          - name: healthcheck
            type: cmdProbe
            mode: Edge
            runProperties:
              probeTimeout: 5s
              retry: 0
              interval: 1s
              stopOnFailure: false
            cmdProbe/inputs:
              command: ./healthcheck -name aws-ec2
              source:
                image: artifactory.sdlc.ctl.gcp.db.com/dkr-public-local/com/db/chaos-hce/thirdparty/harness/chaos-go-runner:1.38.2
                inheritInputs: true
                volumeMount:
                  - mountPath: /var/run/secrets/eks.amazonaws.com/serviceaccount
                    name: aws-iam-token
                    readOnly: true
                volumes:
                  - name: aws-iam-token
                    projected:
                      defaultMode: 420
                      sources:
                        - serviceAccountToken:
                            audience: sts.amazonaws.com
                            expirationSeconds: 86400
                            path: token
              comparator:
                type: string
                criteria: contains
                value: "[P000]"
