---
apiVersion: litmuschaos.io/v1alpha1
kind: ChaosEngine
metadata:
  name: ecs-container-memory-hog
  namespace: default
  labels:
    name: ecs-container-memory-hog
    app.kubernetes.io/part-of: litmus
    app.kubernetes.io/component: experiment-job
    app.kubernetes.io/version: ci
    app.kubernetes.io/enableAWSAccessViaSecrets: disable
spec:
  engineState: "active"
  terminationGracePeriodSeconds: 30
  chaosServiceAccount: litmus-admin
  experiments:
    - name: ecs-container-memory-hog
      image: artifactory.sdlc.ctl.gcp.db.com/dkr-public-local/dkr-io/harness/chaos-go-runner:1.54.0
      imagePullPolicy: Always
      args:
        - -c
        - ./experiments -name ecs-container-memory-hog
      command:
        - /bin/bash
      spec:
        components:
          env:
            - name: TOTAL_CHAOS_DURATION
              value: "30"

            - name: RAMP_TIME
              value: ""

            - name: CLUSTER_NAME
              value: ""

            - name: SERVICE_NAME
              value: ""

            # set memory consumption (in MBs) as desired
            - name: MEMORY_CONSUMPTION
              value: "100"

            - name: MEMORY_PERCENTAGE
              value: "0"

            - name: NUMBER_OF_WORKERS
              value: "1"

            - name: REGION
              value: ""

            - name: INSTALL_DEPENDENCIES
              value: "True"

            - name: DEFAULT_HEALTH_CHECK
              value: "false"

            - name: AWS_SHARED_CREDENTIALS_FILE
              value: "/tmp/cloud_config.yml"

            - name: INSTALL_DEPENDENCIES
              value: "True"

            - name: SEQUENCE
              value: "parallel"
          projectedVolumes:
            - name: aws-iam-token
              mountPath: /var/run/secrets/eks.amazonaws.com/serviceaccount
              readOnly: true
              projected:
                defaultMode: 420
                sources:
                  - serviceAccountToken:
                      audience: sts.amazonaws.com
                      expirationSeconds: 86400
                      path: token
