---
apiVersion: litmuschaos.io/v1alpha1
kind: ChartServiceVersion
metadata:
  name: byoc-injector
  version: 0.1.0
  annotations:
    categories: "Kubernetes"
    vendor: "Harness"
spec:
  displayName: BYOC Injector
  categoryDescription: |
    This experiment enables the execution of custom chaos faults using a specialized helper pod
  keywords:
    - Kubernetes
  plan:
    - enterprise
  platforms:
    - GKE
    - Minikube
    - Packet(Kubeadm)
    - EKS
    - AKS
  minKubeVersion: 1.12.0
  labels:
    app.kubernetes.io/component: chartserviceversion
    app.kubernetes.io/version: ci
  links:
    - name: Documentation
      url: https://docs.harness.io/category/kl0mxwpfw1-hce-category
  icon:
    - url:
      mediatype: ""
