---
apiVersion: litmuschaos.io/v1alpha1
kind: K8sFault
metadata:
  name: byoc-injector
spec:
  definition:
    chaos:
      experiment: byoc-injector
      serviceAccountName: litmus-admin
      image: artifactory.sdlc.ctl.gcp.db.com/dkr-public-local/dkr-io/harness/chaos-ddcr-faults:1.54.0
      imagePullPolicy: Always
      env:
        - name: TOTAL_CHAOS_DURATION
          value: "60"

        - name: LIB_IMAGE
          value: artifactory.sdlc.ctl.gcp.db.com/dkr-public-local/dkr-io/harness/chaos-ddcr-faults:1.54.0

        - name: COMMAND
          value: "/bin/bash"

        - name: ARGS
          value: "-c,./helpers -name byoc-injector"

        # Period to wait before and after injection of chaos in sec
        - name: RAMP_TIME
          value: ""
