---
apiVersion: litmuschaos.io/v1alpha1
kind: ChaosEngine
metadata:
  name: gcp-vm-instance-stop
  labels:
    name: gcp-vm-instance-stop
    app.kubernetes.io/part-of: litmus
    app.kubernetes.io/component: experiment-job
    app.kubernetes.io/version: ci
spec:
  engineState: "active"
  terminationGracePeriodSeconds: 30
  chaosServiceAccount: gcp-vm-instance-stop-sa
  experiments:
    - name: gcp-vm-instance-stop
      image: artifactory.sdlc.ctl.gcp.db.com/dkr-public-local/com/db/chaos-hce/thirdparty/harness/chaos-go-runner:1.38.2
      imagePullPolicy: Always
      args:
        - -c
        - ./experiments -name gcp-vm-instance-stop
      command:
        - /bin/bash
      spec:
        components:
          env:
            - name: TOTAL_CHAOS_DURATION
              value: "30"

            - name: CHAOS_INTERVAL
              value: "30"

            # parallel or serial; determines how the VM instances are terminated, all at once or one at a time
            - name: SEQUENCE
              value: "parallel"

            # period to wait before and after injection of chaos in sec
            - name: RAMP_TIME
              value: ""

            # enable or disable; shall be set to enable if the target instances are a part of a managed instance group
            - name: MANAGED_INSTANCE_GROUP
              value: "disable"

            # Instance name of the target VM instance(s)
            # Multiple instance names can be provided as comma separated values ex: instance1,instance2
            - name: VM_INSTANCE_NAMES
              value: ""

            # GCP project ID to which the VM instances belong
            - name: GCP_PROJECT_ID
              value: ""

            # Instance zone(s) of the target VM instance(s)
            # If more than one instance is targetted, provide zone for each in the order of their
            # respective instance name in VM_INSTANCE_NAME as comma separated values ex: zone1,zone2
            - name: ZONES
              value: ""

            - name: DEFAULT_HEALTH_CHECK
              value: "false"

            # parallel or serial; determines how chaos is injected
            - name: SEQUENCE
              value: "parallel"
          secrets:
            - name: cloud-secret
              mountPath: /tmp/
        probe:
          - name: healthcheck
            type: cmdProbe
            mode: Edge
            runProperties:
              probeTimeout: 5s
              retry: 0
              interval: 1s
              stopOnFailure: false
            cmdProbe/inputs:
              command: ./healthcheck -name gcp-vm
              source:
                image: artifactory.sdlc.ctl.gcp.db.com/dkr-public-local/com/db/chaos-hce/thirdparty/harness/chaos-go-runner:1.38.2
                inheritInputs: true
              comparator:
                type: string
                criteria: contains
                value: "[P000]"
