---
apiVersion: litmuschaos.io/v1alpha1
kind: ChaosEngine
metadata:
  name: lambda-delete-event-source-mapping
  namespace: default
  labels:
    name: lambda-delete-event-source-mapping
    app.kubernetes.io/part-of: litmus
    app.kubernetes.io/component: experiment-job
    app.kubernetes.io/version: ci
    app.kubernetes.io/enableAWSAccessViaSecrets: disable
spec:
  engineState: "active"
  terminationGracePeriodSeconds: 30
  chaosServiceAccount: litmus-admin
  experiments:
    - name: lambda-delete-event-source-mapping
      image: artifactory.sdlc.ctl.gcp.db.com/dkr-public-local/com/db/chaos-hce/thirdparty/harness/chaos-go-runner:1.41.0
      imagePullPolicy: Always
      args:
        - -c
        - ./experiments -name lambda-delete-event-source-mapping
      command:
        - /bin/bash
      spec:
        components:
          env:
            - name: TOTAL_CHAOS_DURATION
              value: "30"

            # Period to wait before and after injection of chaos in sec
            - name: RAMP_TIME
              value: ""

            # provide the target function name
            - name: FUNCTION_NAME
              value: ""

            # provide the uuid of event source mappings
            - name: EVENT_UUIDS
              value: ""

            # provide the region name of the instance
            - name: REGION
              value: ""

            # provide the sequence
            - name: SEQUENCE
              value: "parallel"

            # Provide the path of AWS credentials mounted from secret
            - name: AWS_SHARED_CREDENTIALS_FILE
              value: "/tmp/cloud_config.yml"

            - name: SEQUENCE
              value: "parallel"
          projectedVolumes:
            - name: aws-iam-token
              mountPath: /var/run/secrets/eks.amazonaws.com/serviceaccount
              readOnly: true
              projected:
                defaultMode: 420
                sources:
                  - serviceAccountToken:
                      audience: sts.amazonaws.com
                      expirationSeconds: 86400
                      path: token
