---
apiVersion: litmuschaos.io/v1alpha1
kind: ChartServiceVersion
metadata:
  createdAt: 2022-11-11T10:28:08Z
  name: lambda-delete-event-source-mapping
  version: 0.1.0
  annotations:
    categories: AWS
    vendor: Harness
spec:
  displayName: Lambda Delete Event Source Mapping
  categoryDescription: |
    This fault causes removal of an event source mapping for a certain chaos duration.
    - Causes deletion of event source mapping from a lambda function before re-attaching it after a specific chaos duration.
    - It helps to check the performance/behavior of the lambda function when event source mapping is disconnected.
  keywords:
    - AWS
  plan:
    - enterprise
  platforms:
    - AWS
  experiments:
    - aws-lambda-delete-event-source-mapping
  chaosType: infra
  labels:
    app.kubernetes.io/component: chartserviceversion
    app.kubernetes.io/version: ci
  links:
    - name: Documentation
      url: https://docs.harness.io/category/kl0mxwpfw1-hce-category
  icon:
    - url:
      mediatype: ""
