---
apiVersion: litmuchaos.io/v1alpha1
kind: ChartServiceVersion
metadata:
  createdAt: 2023-04-02T00:00:00Z
  name: ecs-update-container-timeout
  version: 0.1.0
  annotations:
    categories: AWS
    vendor: Harness
spec:
  displayName: ECS Update Container Timeout
  categoryDescription: |
    ECS update container timeout fault disrupts the state of AWS ECS service. This fault injects failures when updating the timeout of a container running on a specified service in the ECS cluster.
    - It helps to check the ability of the task/application running on the ECS cluster to handle timeout changes gracefully.
  keywords:
    - AWS
  plan:
    - team
  platforms:
    - GKE
    - EKS
    - AKS
  experiments:
    - aws-ecs-update-container-timeout
  labels:
    app.kubernetes.io/component: chartserviceversion
    app.kubernetes.io/version: ci
  links:
    - name: Documentation
      url: https://docs.harness.io/category/kl0mxwpfw1-hce-category
  icon:
    - url:
      mediatype: ""
