---
apiVersion: litmuschaos.io/v1alpha1
kind: ChaosEngine
metadata:
  name: pod-network-partition
  namespace: default
  labels:
    name: pod-network-partition
    app.kubernetes.io/part-of: litmus
    app.kubernetes.io/component: experiment-job
    app.kubernetes.io/version: ci
spec:
  # It can be active/stop
  engineState: "active"
  terminationGracePeriodSeconds: 30
  appinfo:
    appns: ""
    # FYI, To see app label, apply kubectl get pods --show-labels
    applabel: ""
    appkind: ""
  chaosServiceAccount: pod-network-partition-sa
  experiments:
    - name: pod-network-partition
      image: artifactory.sdlc.ctl.gcp.db.com/dkr-public-local/dkr-io/harness/chaos-go-runner:1.41.0
      imagePullPolicy: Always
      args:
        - -c
        - ./experiments -name pod-network-partition
      command:
        - /bin/bash
      spec:
        components:
          env:
            - name: TOTAL_CHAOS_DURATION
              value: "60" # in seconds

            # time period to wait before and after injection of chaos in sec
            - name: RAMP_TIME
              value: ""

            - name: DEFAULT_HEALTH_CHECK
              value: "false"

            # provide the destination ips
            # chaos injection will be triggered for these destination ips
            - name: DESTINATION_IPS
              value: ""

            # provide the destination hosts
            # chaos injection will be triggered for these destination hosts
            - name: DESTINATION_HOSTS
              value: ""

            # provide network policy type
            # support ingress, egress, all values
            - name: POLICY_TYPES
              value: "all"

            # provide labels of the destination pods
            - name: POD_SELECTOR
              value: ""

            # provide labels the destination namespaces
            - name: NAMESPACE_SELECTOR
              value: ""

            # provide comma separated ports
            - name: PORTS
              value: ""
