---
apiVersion: litmuschaos.io/v1alpha1
kind: ChaosEngine
metadata:
  name: node-io-stress
  namespace: default
  labels:
    name: node-io-stress
    app.kubernetes.io/part-of: litmus
    app.kubernetes.io/component: experiment-job
    app.kubernetes.io/version: ci
spec:
  # It can be active/stop
  engineState: "active"
  terminationGracePeriodSeconds: 30
  #ex. values: ns1:name=percona,ns2:run=nginx
  auxiliaryAppInfo: ""
  chaosServiceAccount: node-io-stress-sa
  experiments:
    - name: node-io-stress
      image: artifactory.sdlc.ctl.gcp.db.com/dkr-public-local/com/db/chaos-hce/thirdparty/harness/chaos-go-runner:1.41.0
      imagePullPolicy: Always
      args:
        - -c
        - ./experiments -name node-io-stress
      command:
        - /bin/bash
      spec:
        components:
          env:
            - name: TOTAL_CHAOS_DURATION
              value: "120"

            ## specify the size as percentage of free space on the file system
            ## default value 90 (in percentage)
            - name: FILESYSTEM_UTILIZATION_PERCENTAGE
              value: "10"

            ## we can specify the size in Gigabyte (Gb) also in place of percentage of free space
            ## NOTE: for selecting this option FILESYSTEM_UTILIZATION_PERCENTAGE should be empty
            - name: FILESYSTEM_UTILIZATION_BYTES
              value: ""

            ## Number of core of CPU
            - name: CPU
              value: "1"

            ## Total number of workers default value is 4
            - name: NUMBER_OF_WORKERS
              value: "4"

            ## Total number of VM workers
            - name: VM_WORKERS
              value: "1"

            ## enter the comma separated target nodes name
            - name: TARGET_NODES
              value: ""

            - name: NODE_LABEL
              value: ""

            # Period to wait before and after injection of chaos in sec
            - name: RAMP_TIME
              value: ""

            # provide lib image
            - name: LIB_IMAGE
              value: artifactory.sdlc.ctl.gcp.db.com/dkr-public-local/com/db/chaos-hce/thirdparty/harness/chaos-go-runner:1.41.0

            ## percentage of total nodes to target
            - name: NODES_AFFECTED_PERC
              value: ""

            - name: DEFAULT_HEALTH_CHECK
              value: "false"

            ## it defines the sequence of chaos execution for multiple target nodes
            ## supported values: serial, parallel
            - name: SEQUENCE
              value: "parallel"
