apiVersion: litmuschaos.io/v1alpha1
kind: ChaosEngine
metadata:
  name: nginx-chaos
  namespace: default
spec:
  components:
    runner:
      # secret name for the runner image, if using private registry
      imagePullSecrets:
      - name: regcred
      runnerAnnotations:
        sidecar.istio.io/inject: "false"
  # It can be active/stop
  engineState: 'active'
  chaosServiceAccount: ebs-loss-by-id-sa
  experiments:
    - name: ebs-loss-by-id
      spec:
        components:
          # secret name for the experiment image, if using private registry
          experimentImagePullSecrets:
          - name: regcred
          experimentAnnotations:
            sidecar.istio.io/inject: "false"
          env: 
            # set chaos duration (in sec) as desired
            - name: TOTAL_CHAOS_DURATION
              value: '30'

            # set chaos duration (in sec) as desired
            - name: CHAOS_INTERVAL
              value: '30'              

            # set target ebs volume ID  
            - name: EBS_VOLUME_ID
              value: ''

            # provide the region name of the instance
            - name: REGION
              value: ''
