---
apiVersion: litmuchaos.io/v1alpha1
kind: K8sFault
metadata:
  name: ec2-stop-by-tag
spec:
  definition:
    chaos:
      experiment: ec2-stop-by-tag
      serviceAccountName: litmus-admin
      image: artifactory.sdlc.ctl.gcp.db.com/dkr-public-local/dkr-io/harness/chaos-ddcr-faults:1.54.0
      imagePullPolicy: Always
      env:
        - name: TOTAL_CHAOS_DURATION
          value: "60"

        - name: CHAOS_INTERVAL
          value: "60"

        - name: EC2_INSTANCE_TAG
          value: ""

        - name: REGION
          value: ""

        - name: INSTANCE_AFFECTED_PERC
          value: "0"

        - name: MANAGED_NODEGROUP
          value: ""

        - name: SEQUENCE
          value: "parallel"

        - name: AWS_SHARED_CREDENTIALS_FILE
          value: /tmp/cloud_config.yml

        - name: RAMP_TIME
          value: ""
